### ISSUE TITLE
Implement Keyword in context for search results

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#10]
Can we do this?

Also, can the URL for the search results take one to the location of the hit for the search?

**Comment by wsalesky** [comment]
Yes, I think we can. I will take a look. How is the Syriac search?

**Comment by davidamichelson** [comment]
Okay, but will need some innovation. We can discuss. I think we will want to have * by default rather than optional

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters 
Can I have a few search terms to test the KWIC? (Syriac terms that will show up in multiple records, preferably in multiple locations in a document.)

**Comment by jedwardwalters** [comment]
Sure! No problem. Here are a few you could try:
ܐܓܪܬܐ
ܡܐܡܪܐ
ܗܝܡܢܘܬܐ
ܡܫܝܚܐ

**Comment by wsalesky** [comment]
Excellent! Thank you. Should have something for testing shortly.

**Comment by wsalesky** [comment]
Enabled keyword in context, have not yet hooked up the link to the correct place in the record.

**Comment by jedwardwalters** [comment]
That looks really great.

**Comment by dlschwartz** [comment]
Fantastic!

**Comment by wsalesky** [comment]
I added the div number and also links from results directly to the div in the document.

**Comment by jedwardwalters** [comment]
This is great, @wsalesky. 

I noticed one thing, which is very minor: if a word is in the title, the <div> number search result does not reflect that.

For example, see the search here: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=ܐܓܪܬܐ

The very first entry has 19 as the section number, but the word is actually in the title, not section 19. I don't think this is a huge issue, but I don't want it to be confusing from a user's perspective.

**Comment by wsalesky** [comment]
We can probably fix that.

**Comment by wsalesky** [comment]
Fixed.
