### ISSUE TITLE
Advanced Search - Title

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#101]
The "title" limit on the advanced search isn't working.

**Comment by wsalesky** [comment]
Can you give me a search example and what you get vs. what you expect?

**Comment by jedwardwalters** [comment]
Sure. When I search for the Syriac word ܢܦܫܐ and limit the corpus by author (I'll use Aphrahat as an example), it works perfectly. I get these results:
<img width="1440" alt="screen shot 2018-04-25 at 9 08 30 am" src="https://user-images.githubusercontent.com/11543800/39247850-82a0932c-4868-11e8-9d63-7b80b03f8678.png">

But then when I leave author blank and try to limit by title, it doesn't work. I searched "Demonstrations", "Demonstration 7", and "On Penitents" (the latter two showed up in the author search, so I know they have results).

So, if I were to search for ܢܦܫܐ with "Demonstrations" in the title, I'd hope it returned all results across all the Demonstrations, but if I searched by a single Demonstration (i.e. Dem. 7), I'd expect it to return results from only Dem. 7.

**Comment by jedwardwalters** [comment]
It also doesn't work if I search with Aphrahat as the author *and* try to limit it to a single Demonstration in the title box.

**Comment by wsalesky** [comment]
Okay, for some reason the advanced search has the following logic in the title search: 
`tei:body/tei:div1/tei:head/tei:title`

I'm guessing we actually want to search:
`tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title`

Is that correct?

**Comment by wsalesky** [comment]
@jedwardwalters Updated. Please test. Close if fixed.

**Comment by jedwardwalters** [comment]
Okay. It works now. By the way, I like the faceted search results on this. That will be very handy as the corpus continues to grow!
