### ISSUE TITLE
Typo in page meta-data?

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#102]
Okay, so this is strange, but I just noticed something in my search history. The title of the index page  in the meta-data of the website appears to have a typo: "projectl" instead of "project". 

I've never noticed this before, so maybe it's something with my browser (just switched from chrome to firefox).

See screenshots here:
<img width="413" alt="screen shot 2018-04-25 at 9 29 47 am" src="https://user-images.githubusercontent.com/11543800/39249135-f42c802a-486b-11e8-9952-aa3ff69ce777.png">
<img width="697" alt="screen shot 2018-04-25 at 9 33 11 am" src="https://user-images.githubusercontent.com/11543800/39249136-f43b86c4-486b-11e8-9dc1-d791b9121f5e.png">

**Comment by wsalesky** [comment]
Fixed.
