### ISSUE TITLE
Footnote justification

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#106]
For text editions with more substantive footnotes (like the new text that you added the front matter for), I think we will want them to be left justified rather than right. But for those texts that we added earlier with footnotes, I like them right justified.

Is there something I can add to the `<note>` coding to distinguish between these kinds of texts that will make this easy on you?

**Comment by wsalesky** [comment]
Is there a way to distinguish between 'substantive' and not? A number of footnotes? Otherwise you would have to add something perhaps to the `@place` attribute? ex: `place="foot left"`

**Comment by jedwardwalters** [comment]
Okay. Let's hold off on this for now. I'm working on another text with a critical apparatus (variant readings from multiple sources), and that will likely be a different kind of note display. So let me get the test version worked out, then we can tackle these together.

But the place attribute seems like an okay solution.

**Comment by jedwardwalters** [comment]
@wsalesky Just following up here: do you think the `place="foot left"` is the best way to handle this?

**Comment by wsalesky** [comment]
Let's test it on one and see if I can get it to behave.

**Comment by jedwardwalters** [comment]
@wsalesky I thought of a possible solution here. I think this will only be an issue on our "born digital editions," which will generally include some kind of preface, likely with more substantive footnotes, and then a more traditional apparatus with variant readings.

So, my proposal is: what if we had two different sections at the bottom (which we could distinguish with the "place" attribute on the note element): 
Notes (for more substantive footnotes and annotations) - justified left
Apparatus (for variant readings) - justified right

@davidamichelson Before Winona does anything here, can you weigh in on this issue? Here's the deal: up to this point, all of the texts we've encoded with critical apparatus (like Mingana's volumes) have had footnotes justified to the right. However, in the text I edited, the notes I included look a little odd with right justification: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/372.html

Any thoughts on this?

**Comment by jedwardwalters** [comment]
Then again, perhaps just left-justifying all notes and not having two different sections might be a more elegant solution.

**Comment by jedwardwalters** [comment]
Here's an example of a text with mostly just critical apparatus notes, justified-right, as an example for comparison with /372 above:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/365.html

**Comment by davidamichelson** [comment]
I think we should justify them all left rather than two directions. Even
the critical apparatus ones justify left when you use the pop and they look
okay.

**Comment by davidamichelson** [comment]
FYI on 372, Jamey should note one have a period at the end?

On Mon, May 7, 2018 at 3:00 PM, David Michelson <david.a.michelson@gmail.com

**Comment by jedwardwalters** [comment]
@davidamichelson I agree. I think that is a better solution than the two sections.
@wsalesky Sorry, I know we went back on forth on this previously. Can we just set all footnote displays to justify to the left?

**Comment by jedwardwalters** [comment]
@davidamichelson And yes, that first footnote is missing a period. Nice catch!

**Comment by wsalesky** [comment]
@jedwardwalters is there an action item here, I think currently all items justify left already? Let me know if not (and link to an example for me to check)

**Comment by davidamichelson** [comment]
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/372 justifies
right. (I think they all justify right?)

**Comment by wsalesky** [comment]
Done.

**Comment by jedwardwalters** [comment]
Looks good. Thanks, @wsalesky.

**Comment by jedwardwalters** [comment]
Might be a problem in the code. I’ll have a look tonight.

**Comment by wsalesky** [comment]
Fixed. I had to force the left alignment with this `&#8206;`

**Comment by davidamichelson** [comment]
Alas, and now the footnotes are maybe not wrapped with the Syriac script codes so they do not change font or use the default embeddedfont

**Comment by davidamichelson** [comment]
While we are at it, the Sedra Popup Box also does not use the default Syriac font. Can we make it do so?

**Comment by wsalesky** [comment]
Footnotes have been updated.

**Comment by wsalesky** [comment]
We currently use the HTML that Sedra sends us, no post processing. If George adds  `@lang='syr'` to the Syriac text they should automatically use the correct fonts.

**Comment by davidamichelson** [comment]
Great, I sent an e-mail.
