### ISSUE TITLE
creative commons url needs resizing/break

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriac-corpus-app#107]
The cc url runs out of the How to Cite box. Perhaps we could resize it or have some way to break to a new line. I'm not sure what will be best for scaling the page.

![citation](https://user-images.githubusercontent.com/4984270/39381650-6f3e8b10-4a28-11e8-9662-23c046473c55.JPG)

**Comment by wsalesky** [comment]
@dlschwartz I don't think this is an issue any longer.
