### ISSUE TITLE
Style Sheets for TEI:biblStruct

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#108]
@wsalesky We are revising how the corpus uses biblStruct encoded data. In all cases, @jedwardwalters will ensure that any data encoded in a TEI:biblSruct matches exactly with what is found in the TEI:body of the entry in the Syriaca.org Bibl module.

For example the citation information in http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/53.tei //sourceDesc will match: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1765/tei //body

Because both projects will have the same data structure, then please use the stylesheets for preferred citation from the Syriaca Bibl Module to render citation information in the Corpus page. For example currently in the box which contains "Source: D. Alphonsi Mingana ed., "."_Narsai Doctoris Syri Homiliae et Carmina_, (Mosul: Typis Fratrum Praedicatorum, 1905)" on http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/53 the biblStruct should instead render as "Source: Alphonse Mingana, ed., _Narsai doctoris Syri homiliæ et carmina_, (Mausilii: Typis Fratrum Prædicatorum, 1905)." which is the format found as the preferred citation on http://wwwb.library.vanderbilt.edu/bibl/1765.

**Comment by davidamichelson** [comment]
One confusion is why the preferred formats for http://wwwb.library.vanderbilt.edu/bibl/2329 and http://wwwb.library.vanderbilt.edu/bibl/1765 are different. They should each be corrected as:

Alphonse Mingana, ed., _Narsai doctoris Syri homiliæ et carmina_, (Mausilii: Typis Fratrum Prædicatorum, 1905).

and

Jean Parisot, ed., _Aphraatis Sapientis Persae Demonstrationes_, Patrologia Syriaca, vol. 1.1 (Paris: Firmin-Didot, 1894).

**Comment by wsalesky** [comment]
Fixed.

**Comment by davidamichelson** [comment]
Forgot to say this this morning! They look perfect! Thanks @wsalesky !!
