### ISSUE TITLE
Right hand box re-structuring

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#109]
@wsalesky This is an issue that's likely going to have multiple parts. I'm going to start with the big picture re-alignment, and then we'll go from there with other more specific issues as needed. There are a few coding tweaks I'll have to make as well to make all of this work correctly.

1. The top box (the one that has "Stable Identifiers") needs a label in the grey bar at the top (like the box below it: "How to Cite This Electronic Edition:). The label for the top box should be: "About This Digital Text"

2. We want to take some of the information from the "How to Cite" box and move it up to the "About This Digital Text" box. So, the contents of the top box should include (we can make this box expandable/collapsable if it's too long):

**Stable Identifiers**
Corpus Text ID: [corpus URI]
NHSL Work ID(s): [work URI]

**Source**: [Source info. for example: Alphonse Mingana, ed. Narsai doctoris Syri homiliæ et carmina. Mausilii: Typis Fratrum Prædicatorum, 1905.] See issues #108 #111 

**Type of Text**: 
[This will be encoded somewhere]

**Status**:
[This will be encoded somewhere]

**Preparation of Electronic Edition**:
TEI XML encoding by James E. Walters.
Syriac text transcribed by [name].
[Note: this info will still come from the respStmt in the titleStmt of the TEI header]

**Open Access and Copyright**:
(inserted from the TEIHeader /TEI/teiHeader/fileDesc/publicationStmt/availability/ab/note = This electronic edition is designed for open access reuse. The Syriac base text is in the public domain. The TEI XML edition is copyrighted by James E. Walters and released under a under a Creative Commons Attribution 4.0 International license (CC BY 4.0). The HTML page is copyrighted by Vanderbilt University and released under a under a Creative Commons Attribution 4.0 International Public License (CC-BY 4.0, https://creativecommons.org/licenses/by/4.0/). Attribution for reuse should follow the suggested citation and also credit the copyright holder of the TEI XML edition.

Winona, please add [Logo] 

3. The sections "Additional Credit" and "Copyright..." should be taken out of the second box.
4. The bibliographic structure for the How to Cite box is going to change a bit. See  issue #108  that @davidamichelson created.

**Comment by davidamichelson** [comment]
@jedwardwalters just to clarify issue #108 is about the source information for the "About This Digital Text" not about the How to Cite box. I will write another issue as #110

**Comment by jedwardwalters** [comment]
Yes, thanks for that clarification. I got my wires crossed in my haste to post this issue before I left the office.

**Comment by wsalesky** [comment]
Initial changes made. Still waiting for some info to be populated in XML.

**Comment by jedwardwalters** [comment]
Sorry. Didn't mean to hit "close"!

**Comment by wsalesky** [comment]
@jedwardwalters @davidamichelson Are we good on this one? There is another open issue for specifics remaining in box, but I think this one can be closed.

**Comment by jedwardwalters** [comment]
Yes, I think so. I'll go ahead and close. We can address any remaining things elsewhere in more specific issues.
