### ISSUE TITLE
How to Cite Box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#110]
@wsalesky Please revise the scripts for the how to cite box for the corpus based on the following. Please note that there are three possible scenarios the script should handle. All of them are differentiated by the contents of /TEI/teiHeader/fileDesc/editionStmt/respStmt/name

We can explain on Monday if we are meeting then.

**Scenario 1 (Citation which includes a biblStruct from the sourceDesc).**

In this case please use the following text nodes or fixed text to construct the citation:

[/TEI/teiHeader/fileDesc/titleStmt/author]
[/TEI/teiHeader/fileDesc/titleStmt/title/@level="a"] 
[/TEI/teiHeader/fileDesc/editionStmt/respStmt/resp]
[/TEI/teiHeader/fileDesc/sourceDesc] (please use the stylesheet used to generate the preferred citation from the biblStruct as done on http://wwwb.library.vanderbilt.edu/bibl/2329, see issue #111 )
in The Oxford-BYU Syriac Corpus (this is fixed prose)
last modified (this is fixed prose)
[/TEI/teiHeader/revisionDesc/change[1]] (use value of @when) 
[/TEI/teiHeader/fileDesc/publicationStmt/idno[1]/@type="URI']

Please construct two types of citation (as in our other projects). One is a "note" style separated by commas. The other is a "bibliography" style separated by periods and capitalization (note that you will need to capitalize the initial letter of [/TEI/teiHeader/fileDesc/editionStmt/respStmt/resp])

Examples based on https://syriaccorpus.org/1/tei

Note:
Aphrahat, “Demonstration 1: On Faith - ܬܚܘܝܬܐ ܕܗܝܡܢܘܬܐ,” based upon Jean Parisot, ed. _Aphraatis Sapientis Persae Demonstrationes_, Patrologia Syriaca, vol. 1.1 (Paris: Firmin-Didot, 1894), in The Oxford-BYU Syriac Corpus, last modified July 4, 2017, https://syriaccorpus.org/1. 

Bibliography:
Aphrahat. “Demonstration 1: On Faith - ܬܚܘܝܬܐ ܕܗܝܡܢܘܬܐ.” Based upon Jean Parisot, ed. _Aphraatis Sapientis Persae Demonstrationes_, Patrologia Syriaca, vol. 1.1 (Paris: Firmin-Didot, 1894). In The Oxford-BYU Syriac Corpus. Last modified July 4, 2017, https://syriaccorpus.org/1.

Lastly related to scenario 1, here is one question about the XML. We were not sure how to let your script know when to look in the sourceDesc (based on ```<ptr target="sourceDesc"/>``` in TEI/teiHeader/fileDesc/editionStmt/respStmt/name". As a place holder I encoded this, but perhaps you could let me know how to really point at another part of the TEI document or what would be best practice?

```<editionStmt>
                <edition n="0.1"/>
                <respStmt>
                    <resp>based upon</resp>
                    <name><ptr target="sourceDesc"/></name>
                </respStmt>
</editionStmt>

<sourceDesc>
                <biblStruct>
                    <analytic>
                        <editor>D. Ioannes Parisot</editor>
                        <title level="a">Aphraatis Demonstrationes I-XXII</title>
                        <idno type="URI">http://syriaca.org/bibl/2329</idno>
                    </analytic>
                    <monogr>
                        <editor>R. Graffin</editor>
                        <title level="m">Patrologia Syriaca 1.1</title>
                        <imprint>
                            <pubPlace>Paris</pubPlace>
                            <publisher>Firmin-Didot et Socii</publisher>
                            <date when="1894">1894</date>
                        </imprint>
                    </monogr>
                </biblStruct>
</sourceDesc>
```

**Scenario 2 (Citation which does not refer to the sourceDesc).**

In this case please use the following text nodes or fixed text to construct the citation:

[/TEI/teiHeader/fileDesc/titleStmt/author]
[/TEI/teiHeader/fileDesc/titleStmt/title/@level="a"] 
[/TEI/teiHeader/fileDesc/editionStmt/respStmt/resp]
[/TEI/teiHeader/fileDesc/editionStmt/respStmt/name]
in The Oxford-BYU Syriac Corpus (this is fixed prose)
last modified (this is fixed prose)
[/TEI/teiHeader/revisionDesc/change[1]] (use value of @when) 
[/TEI/teiHeader/fileDesc/publicationStmt/idno[1]/@type="URI']

Note:
Anonymous, “Exhortation of the Apostle Peter - ܡܡܠܠܐ ܕܛܘܒܢܐ ܦܬܪܘܣ ܫܠܝܚܐ ܕܥܠ ܡܪܬܝܢܘܬܐ,” edited by James Walters, in The Oxford-BYU Syriac Corpus, last modified April 25, 2018, https://syriaccorpus.org/372. 

Bibliography:
Anonymous. “Exhortation of the Apostle Peter - ܡܡܠܠܐ ܕܛܘܒܢܐ ܦܬܪܘܣ ܫܠܝܚܐ ܕܥܠ ܡܪܬܝܢܘܬܐ.” Edited by James Walters. In The Oxford-BYU Syriac Corpus. Last modified April 25, 2018. https://syriaccorpus.org/372. 

Based on:
```
<editionStmt>
                <edition n="0.1"/>
                <respStmt>
                    <resp>edited by</resp>
                    <name><persName><forename>James</forename>
                        <forename>E.</forename>
                        <surname type="sort">Walters</surname></persName></name>
                </respStmt>
</editionStmt>
```

**Scenario 3 (Citation which includes a TEI:altIdentifier from the sourceDesc).**

In this case please use the following text nodes or fixed text to construct the citation:

[/TEI/teiHeader/fileDesc/titleStmt/author]
[/TEI/teiHeader/fileDesc/titleStmt/title/@level="a"] 
[/TEI/teiHeader/fileDesc/editionStmt/respStmt/resp]
[/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier/@type="preferred"]
in The Oxford-BYU Syriac Corpus (this is fixed prose)
last modified (this is fixed prose)
[/TEI/teiHeader/revisionDesc/change[1]] (use value of @when) 
[/TEI/teiHeader/fileDesc/publicationStmt/idno[1]/@type="URI']

Similar to scenario 1, there is one question about the XML. We were not sure how to let your script know when to look in the sourceDesc (based on ```<ptr target="sourceDesc"/>``` in TEI/teiHeader/fileDesc/editionStmt/respStmt/name". As a place holder I encoded this, but perhaps you could let me know how to really point at another part of the TEI document or what would be best practice?

Note:
Jacob of Serugh, “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ,” transcription from Vat. sir. 117, in The Oxford-BYU Syriac Corpus, last modified April 25, 2018, https://syriaccorpus.org/26.

Bibliography:
Jacob of Serugh. “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ.” Transcription from Vat. sir. 117. In The Oxford-BYU Syriac Corpus, last modified April 25, 2018. https://syriaccorpus.org/26.

Based on:
```<editionStmt>
                <edition n="0.1"/>
                <respStmt>
                    <resp>transcription from</resp>
                    <name><ptr target="sourceDesc"/></name>
                </respStmt>
</editionStmt>

<sourceDesc>
                <msDesc>
                    <msIdentifier>
                        <settlement>Vatican City</settlement>
                        <repository>Vatican Library</repository>
                        <idno type="shelfmark">Syr. 117</idno>
                        <altIdentifier type="preferred">
                            <idno>Vat. sir. 117</idno>
                        </altIdentifier>
                        <altIdentifier>
                            <idno type="URI">http://syriaca.org/manuscript/2294</idno>
                        </altIdentifier>
                    </msIdentifier>
                </msDesc>
</sourceDesc>
```

**Comment by jedwardwalters** [comment]
Thanks for writing this up, Dave. I was going to post this tonight.

**Comment by wsalesky** [comment]
@davidamichelson It might be useful to quickly go over this in our meeting today.

**Comment by wsalesky** [comment]
Updated TEI: 
```

                <edition n="0.1"/>
                <respStmt>
                    <resp>based upon</resp>
                    <name><ptr target="#sourceDesc1"/></name>
                </respStmt>
</editionStmt>

<sourceDesc xml:id="sourcDesc1">
                <biblStruct>
                    <analytic>
                        <editor>D. Ioannes Parisot</editor>
                        <title level="a">Aphraatis Demonstrationes I-XXII</title>
                        <idno type="URI">http://syriaca.org/bibl/2329</idno>
                    </analytic>
                    <monogr>
                        <editor>R. Graffin</editor>
                        <title level="m">Patrologia Syriaca 1.1</title>
                        <imprint>
                            <pubPlace>Paris</pubPlace>
                            <publisher>Firmin-Didot et Socii</publisher>
                            <date when="1894">1894</date>
                        </imprint>
                    </monogr>
                </biblStruct>
</sourceDesc>
```

**Comment by davidamichelson** [comment]
One more request @wsalesky could you please change the "Show Full Publication Information" button to "Show Other Citation Styles"

**Comment by davidamichelson** [comment]
@jedwardwalters Should we move this box above the About this Digital Text?

**Comment by jedwardwalters** [comment]
@wsalesky Okay, I got some stuff ready for testing. Namely files 1-24, 26-27, and 372. Those can be our test run.

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters First pass up on dev, please review for errors. 
Thanks!

**Comment by jedwardwalters** [comment]
@wsalesky I don't think we need the blue status box above "About this digital text"
@davidamichelson what do you think?

**Comment by jedwardwalters** [comment]
@wsalesky I have a question I've been meaning to ask for a while: the Syriac text that shows up in the titles in these boxes looks different on different pages. Is there a coding thing on my end that's making this happen?

**Comment by jedwardwalters** [comment]
@wsalesky Same issues on /27 as on /1 noted above, but one additional thing:
(http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/27.html)

There is extra punctuation in the middle of the citation. In both instances a period needs to be deleted:
<img width="317" alt="screen shot 2018-05-01 at 11 29 10 am" src="https://user-images.githubusercontent.com/11543800/39479435-3b3a41b6-4d33-11e8-8c49-88516b5151a3.png">

**Comment by wsalesky** [comment]
@jedwardwalters Thanks!  

Can you give me some examples of the Syriac text looking different? There may be some conflicting CSS styles. 

Also @davidamichelson if I remove the () around the ed it will effect Syriaca.org as well, if we are keeping the bibliographic xslt's synced. Is that going to be a problem? 

Will get to the others shortly. Thanks for reviewing!

**Comment by jedwardwalters** [comment]
@wsalesky On the titles, compare:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/26.html
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/27.html

This may just be an issue on the coding side. But in general, the Syriac text in the How to Cite box looks a little too large to me. Is it possible to make it a little smaller there without messing it up elsewhere?

**Comment by wsalesky** [comment]
@jedwardwalters Yes, I think the titles in the citations are in general on the large side. I will look into that. The difference in appearance in the above records is that 26 is encoded as: 
`<foreign xml:lang="syr">ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ</foreign>`

and 27: 
`<foreign>
ܥܠ ܓܠܝܢ̈ܐ ܐܠܗܝ̈ܐ ܕܗܘܘ ܠܘܬ ܐܒܪܗܡ
</foreign>`

As you an see 27 does not specify Syriac as the language. To get the Syriac fonts applied by the css we need the xml:lang attribute. Otherwise you get whatever your browse has for the Syriac.

**Comment by jedwardwalters** [comment]
Got it. Thanks. I'll take care of that.

**Comment by wsalesky** [comment]
I made the css font size smaller for the left hand menu (for Syriac font). So anything tagged with @xml:lang='syr' should render a little smaller in those boxes. Let me know if you would like it even smaller (or bigger).

**Comment by jedwardwalters** [comment]
@wsalesky That looks great to me.

**Comment by davidamichelson** [comment]
Okay, I followed all of this but think it will be easier to discuss in person. One comment, the () around the ed. can go away, it is confusing because we seem to have three! stylesheets still:
 
compare the preferred citation for this source:

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1765
This is correct: 
Alphonse Mingana, ed., Narsai doctoris Syri homiliæ et carmina, (Mausilii: Typis Fratrum Prædicatorum, 1905). 
And appears correct on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/1765

The same source appears incorrectly (missing a comma before the "ed." and the closing period) in the search results here:
http://wwwb.library.vanderbilt.edu/bibl/search.html?q=Mingana
and here: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=Mingana
 Alphonse Mingana ed., Narsai doctoris Syri homiliæ et carmina (Mausilii: Typis Fratrum Prædicatorum, 1905)

The same source appears incorrectly here with the extra parens:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/53
Alphonse Mingana (ed.), Narsai doctoris Syri homiliæ et carmina (Mausilii: Typis Fratrum Prædicatorum, 1905).

**Comment by jedwardwalters** [comment]
@davidamichelson Is that really the correct preferred citation with the comma after the title (i.e. after carmina) when the next thing is a parentheses? It doesn't seem to me like that comma should be there.

**Comment by davidamichelson** [comment]
@jedwardwalters @wsalesky Yes good catch jamey, okay so we need the preferred citation to be:

 Alphonse Mingana, ed., Narsai doctoris Syri homiliæ et carmina (Mausilii: Typis Fratrum Prædicatorum, 1905).

No comma before the parens.

**Comment by davidamichelson** [comment]
Yes this can be closed, there is a new issue but I will make a separate issue.
