### ISSUE TITLE
Fixing Style Sheets for Preferred Citation on Bibl Module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#111]
related to issue #108 please fix the style sheet on both the Bibl Module and the Corpus (sorry to post only here) for http://wwwb.library.vanderbilt.edu/bibl/2329

Currently the preferred citation reads:

Jean Parisot, ed. _Aphraatis Sapientis Persae Demonstrationes_. , Patrologia Syriaca, vol. 1.1 ( Paris: Firmin-Didot, 1894). 

The corrected version needs to make 4 changes (add comma after "ed.", delete "." and whitespace after Demonstrationes and delete the whitespace between "(" and "Paris"):

Jean Parisot, ed., _Aphraatis Sapientis Persae Demonstrationes_, Patrologia Syriaca, vol. 1.1 (Paris: Firmin-Didot, 1894).

**Comment by wsalesky** [comment]
Fixed.

**Comment by jedwardwalters** [comment]
@wsalesky It looks like there's still a space between ( and Paris near the end of the source citation.

**Comment by wsalesky** [comment]
@jedwardwalters  Sorry, where are you seeing this? (Link?)

**Comment by jedwardwalters** [comment]
@wsalesky Oh, my bad. I should have included that:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/1.html

<img width="313" alt="screen shot 2018-04-30 at 8 53 15 am" src="https://user-images.githubusercontent.com/11543800/39428064-12a19a86-4c54-11e8-9a58-0a4c7e0172b4.png">

**Comment by wsalesky** [comment]
@jedwardwalters Thanks. Looks like the new stylesheet just didn't make it over. Fixed now.
