### ISSUE TITLE
Linked Open Data Box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#114]
@wsalesky I think we are ready to plug the Linked Open Data side bar from GEDSH into the corpus. It should go in its own box on the right, below the How to Cite Box. Would you mind please plugging in what you have now (probaby nothing will work) and we can discuss at our next meeting how to scrape the corpus TEI document for URIS. The count functions we worked out for the SPARQL queries should remain the same.

**Comment by davidamichelson** [comment]
@wsalesky wait I am an idiot, it is already there! I am not sure how I missed it!

**Comment by davidamichelson** [comment]
Let's review how it is working on Monday.

**Comment by davidamichelson** [comment]
List of paths to search for syriaca.org URIS:

Any @ref
/TEI/teiHeader/fileDesc/titleStmt/title/@ref

Any idno/@type="URI"()

**Comment by davidamichelson** [comment]
Please shorten the pop up to: "This sidebar provides links via Syriaca.org to additional resources beyond this record."

In the box itself: 
Delete "Resources related to other topics in this record." Delete the hide button instead use expand and collapse.

**Comment by wsalesky** [comment]
Updated.
