### ISSUE TITLE
Email addresses

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#115]
@wsalesky We need to create some dedicated email addresses for the Corpus.

I think @davidamichelson mentioned that we might make one through the domain, something like info@syriaccorpus.org, but then that Winona could also make some other addresses through the app. I think, at the very least, we might want:
submissions@syriaccorpus.org
corrections@syriaccorpus.org

And all of these can just be set up to be directed to me--whatever the best way to do that is.

**Comment by wsalesky** [comment]
@jedwardwalters @davidamichelson I can add emails but not create them. I think that will have to be done through the systems dept.

**Comment by davidamichelson** [comment]
Sorry just to clarify, I will create the address and I think that
info@syriaccorpus.org shoudl be enough at first. What Jamey is asking about
is how to let you know what addresses the "Corrections?" button should send
to.

**Comment by jedwardwalters** [comment]
Sorry, @davidamichelson. I must have misunderstood when we had that conversation.

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters I am creating a config file for things we do not want published on github, we will include email addresses in this (and changed how they are handled in other versions of the app). We should discuss where to store this file.

**Comment by davidamichelson** [comment]
Great can you rais this on monday please

**Comment by jedwardwalters** [comment]
I think we can close this now.
