### ISSUE TITLE
About this Digital Text box

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#116]
@wsalesky @davidamichelson 

1. Remove "Stable ID" label completely
2. Left justify Corpus Text ID and NHSL (i.e. remove white space to the left)
3. Make the NHSL URI a live link
4. Make Open access paragraph smaller font

**Comment by wsalesky** [comment]
Done. @jedwardwalters please close if it looks right to you.

**Comment by jedwardwalters** [comment]
This all looks great. Thanks.

**Comment by davidamichelson** [comment]
A couple more thoughts:
1. Should the list of  NHSL URIs also have the titles? For example on http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/121 it lists the Gospel of John URI and also two containing URIs but you can't tell which is which.

2. The "Open Access and Copyright:" still looks too long. Should it be collapsed to:
**Open Access and Copyright:**
This electronic edition is designed for open access reuse. The Syriac base text is in the public domain. The TEI XML edition is copyrighted by James E. Walters and released under a under a Creative Commons Attribution 4.0 International Public License (CC BY 4.0). See details...

The see details would then expand to the rest.

**Comment by davidamichelson** [comment]
Okay, thinking about how to do the shortening of the "Open Access and Copyright:" section. I will experiment in record 100 with putting the statement in two notes. Just include TEI:note[1] before the collapse.

```
<availability>
                    <p/>
                    <licence target="http://creativecommons.org/licenses/by/4.0/">
                        <p>Creative Commons — Attribution 4.0 International — CC BY 4.0</p>
                        <p>https://creativecommons.org/licenses/by/4.0/</p>
                    </licence>
                    <ab>
                        <note>This electronic edition is designed for open access reuse. The Syriac
                            base text is in the public domain. The TEI XML edition is copyrighted by
                            James E. Walters and released under a under a Creative Commons
                            Attribution 4.0 International Public License (CC BY 4.0).</note>
                        </ab>
                    <ab>
                        <note>The HTML page is copyrighted by Vanderbilt University and released under a under a
                            Creative Commons Attribution 4.0 International Public License (CC-BY
                            4.0, https://creativecommons.org/licenses/by/4.0/). Attribution for
                            reuse should follow the suggested citation and also credit the copyright
                            holder of the TEI XML edition.</note>
                    </ab>
                </availability>
```

**Comment by davidamichelson** [comment]
@jedwardwalters If this works for Winona, we can include the changes in http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/100 in all the documents.

**Comment by jedwardwalters** [comment]
Okay, sounds good.

**Comment by wsalesky** [comment]
@jedwardwalters @davidamichelson  Updated  "Open Access and Copyright:" section, added Publication date, Status and Text type. Please review and close.

**Comment by jedwardwalters** [comment]
I think this worked like we wanted it to on http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/100.html

But I'll let @davidamichelson weigh in.

**Comment by davidamichelson** [comment]
@wsalesky can you put the " See details..." so that it continues the paragraph instead of starting a new line?

**Comment by davidamichelson** [comment]
GReat work

**Comment by davidamichelson** [comment]
@jedwardwalters Just realizing you will need to go through and change this in all the documents?

'''
<availability>
                    <p/>
                    <licence target="http://creativecommons.org/licenses/by/4.0/">
                        <p>Creative Commons — Attribution 4.0 International — CC BY 4.0</p>
                        <p>https://creativecommons.org/licenses/by/4.0/</p>
                    </licence>
                    <ab>
                        <note>This electronic edition is designed for open access reuse. The Syriac
                            base text is in the public domain. The TEI XML edition is copyrighted by
                            James E. Walters and is reused and released under a under a Creative Commons
                            Attribution 4.0 International Public License (CC BY 4.0).</note>
                        </ab>
                    <ab>
                        <note>The HTML page is copyrighted by Vanderbilt University and released under a under a
                            Creative Commons Attribution 4.0 International Public License (CC-BY
                            4.0, https://creativecommons.org/licenses/by/4.0/). Attribution for
                            reuse should follow the suggested citation and also credit the copyright
                            holder of the TEI XML edition.</note>
                    </ab>
                </availability>
'''

**Comment by jedwardwalters** [comment]
Yep. I can take care of that. I was waiting on final approval of this format. You only made the change in /100 right?

**Comment by davidamichelson** [comment]
Yes that's right

**Comment by jedwardwalters** [comment]
@davidamichelson I have now updated the copyright section in availability across the corpus.

**Comment by jedwardwalters** [comment]
I think we are all good on this issue too.
