### ISSUE TITLE
Small tweaks to How to Cite box

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#117]
@wsalesky @davidamichelson 
1. Remove Editorial Responsibility section (header and names)
2. Move publication date to top

**Comment by davidamichelson** [comment]
Did the Publication Date move up to the About This Digital Text box?

It should perhaps come right after status.

**Comment by jedwardwalters** [comment]
Oh, yeah, I noticed that the date of publication had dropped out too, but I forgot to make a note of it.

**Comment by wsalesky** [comment]
Added
