### ISSUE TITLE
Print to PDF

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#120]
All PDFS need the "About This Digital Text" box information at the end of the document.

On PC, the PDFs still have the sedra links, these should be removed.

**Comment by wsalesky** [comment]
Fixed. https://github.com/srophe/syriac-corpus-app/commit/0740aa1e1fc22102930776931700213308dd424c

**Comment by davidamichelson** [comment]
On Firefox the Print button PDF puts the Info Box on the right, not the bottom.

**Comment by davidamichelson** [comment]
[Gospel of John -.pdf](https://github.com/srophe/syriac-corpus-app/files/1961938/Gospel.of.John.-.pdf)

**Comment by davidamichelson** [comment]
Also the "Click to send to the printer" image is still visible.

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz I think this resolves the remaining Firefox issues.
