### ISSUE TITLE
Top Right Buttons

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#121]
Move "Corrections/Additions" button up and put on the right of the list with printer etc. And shorten to "Corrections?"

After "Corrections" and before printer, please add a "Copy" button that copies to clipboard the contents of the RTF file in plain text. It should have a pop up button that reads "To preserve right-to-left text, paste with options "unformatted text" or "keep text only.""

Shorten Download TEI/XML to just "TEI"

Add a button to the left of "TEI" with download icon and "Text" that downloads an RTF file of the Syriac text and includes the preferred citation at the top.

@jedwardwalters We added some stuff, please feel free to weigh in.

**Comment by jedwardwalters** [comment]
I don't think the copy button needs a ? at the end.

**Comment by jedwardwalters** [comment]
I think this looks good.

**Comment by wsalesky** [comment]
Great, I need to add the functionality for the text serialization and the copy function, so just leave it open for now.

**Comment by davidamichelson** [comment]
Should these buttons go up under the line like the URI Button but justified
right? Also is the URI button redundant?

**Comment by wsalesky** [comment]
Added copy function. Please test. @davidamichelson @jedwardwalters

**Comment by wsalesky** [comment]
@davidamichelson I think we can mark this as resolved?

**Comment by davidamichelson** [comment]
Yes
