### ISSUE TITLE
Documentation Wikis for Corpus

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#122]
@jedwardwalters we talked with @dlschwartz today about issues related to cutting and pasting Syriac out of the corpus and came up with a variety of solutions. It is a headache on mac!!!

Anyway I think one more step is to assemble some help documentation which probably needs to go somewhere in the top menus, probably font-> help which takes you to here: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/documentation/wiki.html?wiki-page=/How-to-view-Syriac-script&wiki-uri=https://github.com/srophe/srophe-app-data/wiki

We need to clean up this wiki to make it corpus specific. Maybe we should also add this help option to the Advanced gear menu?

**Comment by davidamichelson** [comment]
@wsalesky where do we find that wiki? Is it physically separate from the Srophe App?

**Comment by davidamichelson** [comment]
I think this is just using the Syriaca wiki, so we need to make a corpus specific one here https://github.com/srophe/syriac-corpus/wiki

**Comment by davidamichelson** [comment]
Okay, does it look like we can clone a wiki?

**Comment by wsalesky** [comment]
Yes, you can from the wiki page. https://github.com/srophe/srophe-eXist-app/wiki

**Comment by davidamichelson** [comment]
Assinging this to Jamey and me

**Comment by jedwardwalters** [comment]
@davidamichelson Maybe we can chat about this via skype at some point? Just so I understand fully what we're doing.

**Comment by davidamichelson** [comment]
Yes, can we meet this monday at the usual time?

**Comment by jedwardwalters** [comment]
Yes, I can meet at the usual time on Monday.

**Comment by jedwardwalters** [comment]
Clone syriaca.org wiki: https://github.com/srophe/srophe-eXist-app/wiki
Create first page on new wiki
Copy syriaca files into new wiki

**Comment by davidamichelson** [comment]
@jedwardwalters 

Clone  https://github.com/srophe/srophe-eXist-app/wiki and edit it into https://github.com/srophe/syriac-corpus-app/wiki  (This is for technical information for developers mainly)

Clone https://github.com/srophe/srophe-app-data/wiki and edit it into https://github.com/srophe/syriac-corpus/wiki (this has all the definititions of types, terms, info for scholars and editors/encoders)

**Comment by davidamichelson** [comment]
One more note about the section on the current wiki called: 

Editorial Definitions

    Dates
    Frequently Asked Questions
    Headwords
    Language and Script Identifiers
    Place Types
    Relations
    Religious Communities
    Technical Terminology
    TEI Tag usage in Gazetteer
    Syriaca.org API Documentation
    URI Policies
    Using TEI to Catalog Syriac Manuscripts

This section is hard coded in HTML but should be converted to markdown and entered into here: https://github.com/srophe/syriac-corpus/wiki

**Comment by jedwardwalters** [comment]
@davidamichelson @wsalesky @dlschwartz I have now cloned the wikis, and I don't think I broke anything! So hopefully today we can briefly discuss what needs to stay, what needs to be edited, and what can be deleted.

**Comment by jedwardwalters** [comment]
@davidamichelson I took a crack at converting one of the hard coded html pages you listed into markdown in one of the new wikis. See here: https://github.com/srophe/syriac-corpus/wiki/Dates

**Comment by jedwardwalters** [comment]
I have now culled out the documents from Syriaca.org that I don't think we need in the Corpus documentation. Everything remaining will need editing: some of it will be light (just changing syriaca.org language to syriaccorpus.org, etc), but some of it will be completely re-written.

**Comment by wsalesky** [comment]
Now linking to the correct wiki's. http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/documentation/index.html

**Comment by jedwardwalters** [comment]
Thanks. I’m hoping to get these wikis edited this week.

**Comment by jedwardwalters** [comment]
Closing this because wikis are up and running.
