### ISSUE TITLE
Caption for Corpus Header

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#123]
The caption here: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/documentation/wiki.html?wiki-page=&wiki-uri=https://github.com/srophe/srophe-app-data/wiki

is not correct: it reads:
Photo Credit:Decorative Arch, Resafa, Syria. Copyright, Daniel Schwartz.

@jedwardwalters Winona will need text from you.

**Comment by davidamichelson** [comment]
Actually @wsalesky The correct caption (Image Colchester 1932.228 f. 4b ) is found on the landing page. Not sure why the wrong caption there.

**Comment by wsalesky** [comment]
Fixed.
