### ISSUE TITLE
Cull documenation pages

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#124]
Remove unnecessary pages from the documentation folder.  @jedwardwalters

**Comment by jedwardwalters** [comment]
Just so I'm clear, we are talking about this folder, right?
https://github.com/srophe/syriac-corpus-app/tree/master/documentation

**Comment by wsalesky** [comment]
Yes. Delete pages you do not need/want.

**Comment by jedwardwalters** [comment]
Thanks. Just wanted to be sure.
