### ISSUE TITLE
Font size and whitespace for line numbers, page breaks etc.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#128]
@wsalesky @jedwardwalters There are some cut and paste and some formatting issues which are related to the numbering in the corpus. Let's discuss in person.

**Comment by davidamichelson** [comment]
Insert numbers to the right in the RTF file and include a whitespace both in the RTF and the HTML

**Comment by wsalesky** [comment]
@davidamichelson  @jedwardwalters  Added. Please take a look. The .txt view is now available on dev.

**Comment by davidamichelson** [comment]
@wsalesky whitespace in the HTML works fine and the numbers and text cut and paste fine so that is done.

On the .txt download. There are a couple of issues:
1. The button displays in my browser rather that automatic download. I can download by right click, but is there a way to force download?
2. There are no numbers in the .txt version. I think we do want them in there with the same whitespace as the HTML.
3. The .txt has too much whitespace in it. The citation is fine, but for the text itself the layout of the lines (how they wrap) seems to be hardcoded with whitespaces. Can we instead just keep line breaks from the TEI so the text wraps based on the new document when cut and pasted? Do we need to format the page as RTF to do this?
4. The citation at the top is correct, but has no formatting because this is a .txt file. If we more to RTF could we keep the italics on the title?

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters 

1. Done. I have forced the text to download automatically. 
2. I added the numbers in. 
3. Removed excess whitespace
4. To add formatting and create a true RTF version of the citation will take a few hours (5ish). Do you want me to the time invest into that?

**Comment by davidamichelson** [comment]
Thanks! There are still some issues including in issue # 121 so let's
discuss on Monday. This may be good for now! Please keep these open so we
can discuss.

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters Please review spacing and numbering on the dev server version of the text download. If this looks okay I will move it to Production.

**Comment by wsalesky** [comment]
Fixed

**Comment by wsalesky** [comment]
Fixed. Close if the text output looks okay.

**Comment by wsalesky** [comment]
stale issue.
