### ISSUE TITLE
Multipart Search and Browse

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#13]
We need to brainstorm how to allow users to search and also find in browse a large work that contains sub-parts such as the demonstrations as a whole  <title xml:lang="en" level="s" ref="http://syriaca.org/work/8501">The Demonstrations</title>

**Comment by jedwardwalters** [comment]
@wsalesky Any thoughts on this issue? To use the example that Dave gives, this would mean searching all of the texts that fit within the work of the Demonstrations--i.e. texts 1-24 in the corpus. 

For Aphrahat (and thus the demonstrations) it wouldn't be that hard because his is the author of only one corpus, so you could search by just author name. But for other authors with multiple works, each of which entails multiple "texts" in the corpus, we would need to figure this out.

**Comment by wsalesky** [comment]
@jedwardwalters It would be useful to have some examples. We could use the 'larger work' as a 'facet' in browse, or a dropdown option in the search?

**Comment by jedwardwalters** [comment]
Okay, I'll get you some examples later today.

**Comment by wsalesky** [comment]
@jedwardwalters Checking back in on this issue. Still waiting for some examples to test different search strategies.

**Comment by jedwardwalters** [comment]
Thanks for the reminder. Grading midterms today, but I plan to finish all of that today and spend the rest of the week on corpus stuff in preparation for Amsterdam.

**Comment by wsalesky** [comment]
Okay. Just going through my checklist.

**Comment by jedwardwalters** [comment]
@wsalesky Here are a few examples (Let me know if you need more info):

In all of these examples, the larger work titles and URIs are included in the TEI header titleStmt as title level="s" and then the individual titles contained in that work are labeled as title level="a"

**Example 1**
Work: The Demonstrations (http://syriaca.org/work/8501)
Contains: Corpus URIs 1-24

**Example 2**
Work: The Homilies of Mar Narsai (http://syriaca.org/work/8528)
Contains: Corpus URIs 27-56, 58-99, 101-109

**Example 3**
Work: Odes of Solomon (http://syriaca.org/work/8620)
Contains: Corpus URIs 146-185

**Comment by wsalesky** [comment]
@jedwardwalters @davidamichelson I'm back to this issue. I don't think I understand how the this is search is supposed to function. Can you just give a simple walk through of what you want to do, enter search terms as keywords? What limits you would like to add? And then what results you expect to see. 

@davidamichelson Do you think facets on search results with the title of the containing work would be useful? Sort of how it is done on the browse page: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/browse.html?view=title

**Comment by jedwardwalters** [comment]
My initial thought was that if someone searches for "Aphrahat" (for example) in the browse box, the search result would be the "larger work" (The Demonstrations) as opposed to each individual demonstration.

This would be helpful for authors like Ephrem, who have multiple large corpuses. 

Is that what you meant, @davidamichelson? Any thoughts for clarification here?

**Comment by wsalesky** [comment]
@davidamichelson Any feed back on how this should work?

**Comment by wsalesky** [comment]
Add a limit by catalog dropdown on the search page and a facet by catalog and author as on browse.

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters I think this is resolved. Let me know if I misunderstood. 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html

**Comment by jedwardwalters** [comment]
This seems to work fine. @davidamichelson?

**Comment by jedwardwalters** [comment]
I think this is resolved.
