### ISSUE TITLE
"Anonymous" authorship

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#132]
@davidamichelson How do you feel about "Anonymous" being the first thing that shows up here:
<img width="315" alt="screen shot 2018-05-01 at 9 49 16 pm" src="https://user-images.githubusercontent.com/11543800/39501569-b0f75bfe-4d89-11e8-8a64-8e3a34d21fcf.png">

I don't love it. I'm wondering if we want to remove "Anonymous" as the author for all anonymous texts? Or perhaps just set up the display to ignore if author=anonymous? Thoughts?

**Comment by davidamichelson** [comment]
Sounds like a great question for the whole editorial board!

**Comment by dlschwartz** [comment]
Did this get resolved? I would prefer the removal of "Anonymous".

**Comment by jedwardwalters** [comment]
I haven't asked the editorial board, but I think it should just be removed. I can't imagine anyone would argue for keeping it there.

**Comment by dlschwartz** [comment]
Agreed. It would be nice though if browse by author "anonymous" still worked.

**Comment by jedwardwalters** [comment]
Ah, interesting point, Dan.

@wsalesky Would it be difficult to have a setting where we kept the author listed as "Anonymous" for searching/sorting purposes in browse, but not have "Anonymous" appear as the author on the page display for that text? For example, for http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/188, see these two screenshots:
<img width="538" alt="screen shot 2018-05-04 at 11 57 27 am 2" src="https://user-images.githubusercontent.com/11543800/39637972-aa79a6a0-4f92-11e8-8ba3-a4398b0f4548.png">
<img width="339" alt="screen shot 2018-05-04 at 11 57 35 am 2" src="https://user-images.githubusercontent.com/11543800/39637973-aa8a9a00-4f92-11e8-9cb4-861ed733a947.png">

**Comment by jedwardwalters** [comment]
Add `type=`"anonymous"`` on `<author>`

**Comment by jedwardwalters** [comment]
@wsalesky It wouldn't validate the type attribute on author, so I had to use "style" instead
`<author style="anonymous">Anonymous</author>`

**Comment by wsalesky** [comment]
Okay, I will make the changes in the code.

**Comment by wsalesky** [comment]
@jedwardwalters Updated the code. Close if it looks good.

**Comment by davidamichelson** [comment]
@jedwalters not essential, but I wonder if @role might make more sense than
@style?

**Comment by jedwardwalters** [comment]
@davidamichelson Perhaps. I briefly looked through the list of allowed attributes, and none of them struck me as perfect. I'm happy to change it if you think @role is better.

**Comment by davidamichelson** [comment]
I think @role allows you to specif an attribute of the author, which is
this is an anonymous one

**Comment by jedwardwalters** [comment]
Okay. Sounds good. I'm happy to make this change. 
@wsalesky can you update the code to change from `@style` to `@role`? Then I think we can close this, because the display on the current code looks fine to me.

**Comment by jedwardwalters** [comment]
FYI I've changed this in the XML files already.

**Comment by wsalesky** [comment]
@jedwardwalters  Updated the code. Close if it looks good.

**Comment by jedwardwalters** [comment]
@wsalesky I checked on the Book of Steps entries and Odes of Solomon, and those are fine, but for some reason "Anonymous" is still showing up as the author on http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/372.html

I tried doing a hard refresh on that page and it's still showing up.

**Comment by wsalesky** [comment]
Looks like that record did not get loaded to eXist. I manually pushed it.

**Comment by jedwardwalters** [comment]
Looks good now. Thanks.
