### ISSUE TITLE
Project name change

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#134]
@wsalesky It looks like the editorial board has decided to officially change the name of the project from the "Oxford-BYU Syriac Corpus" to the "Digital Syriac Corpus."

We can talk about action steps to reflect this name change across the site at our Monday meeting with @davidamichelson and @dlschwartz

**Comment by wsalesky** [comment]
@jedwardwalters Okay, sounds good.

**Comment by jedwardwalters** [comment]
@wsalesky 
Change Header and Footer
Change in the name of the application in two places in the APP
NEW FOOTER: Digital Syriac Corpus is collaboration of University of Oxford, Brigham Young University, Vanderbilt University, and the Center of Digital Humanities Research (CoDHR) at Texas A&M University. This HTML page is copyrighted by Vanderbilt University and released under a under a Creative Commons Attribution 4.0 International Public License (CC-BY 4.0). The TEI XML editions are copyrighted by the encoders and released under CC-BY 4.0. All Syriac base texts are in the public domain.

**Comment by jedwardwalters** [comment]
For Jamey: do search and replace across the corpus.

**Comment by jedwardwalters** [comment]
FYI: I'm presenting about the corpus at a conference on Friday, so if possible, it would be great to have this done by then.

**Comment by wsalesky** [comment]
@jedwardwalters I think I caught them all. Take a look around and let me know if I missed anything.

**Comment by jedwardwalters** [comment]
Not an issue with the name, but a small thing in the footer:
Digital Syriac Corpus is collaboration of...
needs to add "a" between is and collaboration (i.e.: Digital Syriac Corpus is a collaboration of...)

**Comment by wsalesky** [comment]
@jedwardwalters  Should 'About Digital Syriac Corpus' be 'About the Digital Syriac Corpus' on the home page?

**Comment by jedwardwalters** [comment]
Yeah, I think so.

**Comment by jedwardwalters** [comment]
One other issue: this appears to only be happening on the pages with the actual texts, not the index or browse pages: the title at the very top left is replacing "Digital Syriac Corpus" with the name of the text of that page. See here:
![screen shot 2018-05-07 at 12 15 56 pm](https://user-images.githubusercontent.com/11543800/39712346-afb6cfc0-51f0-11e8-81a6-e944f40d25b9.png)

**Comment by jedwardwalters** [comment]
Looks good to me everywhere I've checked. If I happen to catch anything in the next few days, I'll re-open.
