### ISSUE TITLE
About page / menu

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#136]
@wsalesky Add "About" dropdown menu like the one on syriaca.org
We'll need links for:
Project Overview
Origins of the Project
Support our Work
Contact Us
Documentation
[maybe others, but this is a good start]

**Comment by wsalesky** [comment]
@jedwardwalters Added to dev server. Will add to production once the pages are in place to link to.

**Comment by jedwardwalters** [comment]
Great. Thank you. This will be my primary to-do thing next week after the Kalamazoo conference trip this weekend.

**Comment by jedwardwalters** [comment]
We've got another issue open for issues pertaining to this.
