### ISSUE TITLE
Editorial Board

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#137]
@wsalesky We are making a slight adjustment to the Editorial Board structure, which will affect the display on the index page. The editorial board has voted to make me the general editor for the whole project.

Right now there's just one heading "Editors" will all the board members listed. We now need two identical headers: 1) Editor and 2) Editorial Board:

Editor
James E. Walters, Rochester College

Editorial Board
Prof. David G.K. Taylor, University of Oxford
Prof. Aaron Butts, The Catholic University of America
Prof. Muriel Debié, École pratique des hautes études, Paris
Dr. Kristian S. Heal, Brigham Young University
Dr. George A. Kiraz, Beth Mardutho: The Syriac Institute
Prof. David A. Michelson, Vanderbilt University
Prof. Daniel L. Schwartz, Texas A&M University
Prof. Dr. Dorothea Weltecke, Goethe-Universität, Frankfurt am Main

**Comment by jedwardwalters** [comment]
I'm going to take the "editor in chief" tag off of David Taylor's name in the coding. Let me know if there's a tag I can put on my own `<name>` element that will help you with this display.

**Comment by wsalesky** [comment]
@jedwardwalters The editors are hand coded, so I will just make the change on the index page.

**Comment by jedwardwalters** [comment]
Ah okay. Sounds good. Thanks!

**Comment by jedwardwalters** [comment]
One quick thing: it looks like my name isn’t indented the way the board names are. Please indent the same amount, then you can close this.

**Comment by wsalesky** [comment]
Done

**Comment by jedwardwalters** [comment]
Looks great! Thanks.
