### ISSUE TITLE
How to Cite (definite article?)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#138]
"in Digital Syriac Corpus" or just Digital Syriac Corpus?

I am wondering if we should get rid of the "in" now that there is no definite article? @jedwardwalters 

Current:
Note:
Jacob of Serugh, “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ,” based upon Vat. sir. 117, in Digital Syriac Corpus, last modified May 1, 2018, https://syriaccorpus.org/26.
Bibliography:
Jacob of Serugh. “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ.” Based upon Vat. sir. 117. In Digital Syriac Corpus. Last modified May 1, 2018. https://syriaccorpus.org/26.

Suggested:
Note:
Jacob of Serugh, “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ,” based upon Vat. sir. 117, Digital Syriac Corpus, last modified May 1, 2018, https://syriaccorpus.org/26.
Bibliography:
Jacob of Serugh. “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ.” Based upon Vat. sir. 117. Digital Syriac Corpus. Last modified May 1, 2018. https://syriaccorpus.org/26.

or 

Note:
Jacob of Serugh, “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ,” based upon Vat. sir. 117, published by Digital Syriac Corpus, last modified May 1, 2018, https://syriaccorpus.org/26.
Bibliography:
Jacob of Serugh. “On Joseph (Memra 1) - ܡܺܐܡܪܳܐ ܩܰܕܡܳܝܳܐ ܕܥܰܠ ܝܰܘܣܶܦ.” Based upon Vat. sir. 117. Published by Digital Syriac Corpus. Last modified May 1, 2018. https://syriaccorpus.org/26.

**Comment by jedwardwalters** [comment]
Good idea. I think it will be better without "in".
@wsalesky Can you remove "in/In" from the citation code before "Digital Syriac Corpus"?

**Comment by wsalesky** [comment]
@davidamichelson, @jedwardwalters  Fixed. Closed if it looks good to you.

**Comment by jedwardwalters** [comment]
Looks good to me.
