### ISSUE TITLE
About This Digital Text  > Source: +Manuscript?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#139]
In the "About This Digital Text" box, under "Source:" do we want to add the abbreviation MS?

Current:
Source:
Berlin, Staatsbibliothek zu Berlin 201
(Sachau 165) 

Suggested:
Source:
MS Berlin, Staatsbibliothek zu Berlin 201
(Sachau 165)

**Comment by jedwardwalters** [comment]
Generally that's what we do have in the parenthetical thing. See here:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/30.html

It's just that in this particular case, I coded it so that the alternate name would show up, not the abbreviated one.

**Comment by davidamichelson** [comment]
Okay, this is a bit of a preference, so maybe leave as is?

**Comment by jedwardwalters** [comment]
Sorry, what is the preference? Do we need to change something here?

**Comment by davidamichelson** [comment]
Ah, I meant I defer to your preference as to adding in MS or not.

**Comment by jedwardwalters** [comment]
Oh gosh, then I totally misunderstood your first question. Sorry! Trying to work too quickly and do too many things at once. I'm not sure about adding MS. Do you think it adds clarity? If so, I'm happy to add it.

**Comment by davidamichelson** [comment]
It is not essential. Let's leave it as is.

**Comment by jedwardwalters** [comment]
Okay. Sorry I misread it the first time!
