### ISSUE TITLE
Please align Syriac TEI:head/title text to right

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#14]
see https://github.com/srophe/syriac-corpus/blob/master/data/tei/10.xml#L97-L99

Currently displaying aligned left

**Comment by wsalesky** [comment]
Is there a reason the xml:lang attribute is on the tei:title not the tei:head element? I can force the head to inherit the child xml:lang element, but I wonder if it might be better to just add the xml:lang to the tei:head element? (This is from a purely data handling point of view. )

**Comment by davidamichelson** [comment]
We could do that or we could put both titles in the same head. Let's discuss tomorrow.

**Comment by wsalesky** [comment]
Keep xml:lang on both.

**Comment by jedwardwalters** [comment]
@wsalesky I think we can close this one?

**Comment by wsalesky** [comment]
Okay.
