### ISSUE TITLE
Title in preface not in italics

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#140]
@jedwardwalters I like this preface: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/372 

I notice the title you cite there is not italics. Is it marked as a title in the TEI?

**Comment by jedwardwalters** [comment]
I think it is marked in the TEI, but I'll double check and then check with @wsalesky about styling.

**Comment by jedwardwalters** [comment]
Oh. For some reason it looks like I abbreviated "italic" as "ital" when I did this. Strange. I'll fix that and see if that does it.

**Comment by jedwardwalters** [comment]
Yep, that was the issue. It displays in italics now.
