### ISSUE TITLE
Syriac Search on Production

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#141]
Hi @wsalesky ,

The proximity search is working, but the results aren't always displaying correctly. For example, when I do this search: https://divinity-dev.app.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%22%DC%90%DC%93%DC%AA%DC%AC%DC%9F%2B%DC%A9%DC%AA%DC%9D%DC%AC%DC%97%22&keywordProximity=5&author=&title=&fq=&section=&corpus-uri=&syriaca-uri=&text-id=

It returns the correct text that I was testing, but the results do not display the words in context:

<img width="984" alt="screen shot 2018-05-09 at 10 44 06 pm" src="https://user-images.githubusercontent.com/11543800/39849570-f8170974-53da-11e8-84e7-1c730df0d703.png">

<img width="1158" alt="screen shot 2018-05-09 at 10 43 54 pm" src="https://user-images.githubusercontent.com/11543800/39849572-fad6dee6-53da-11e8-9994-a8fed9e62059.png">

**Comment by jedwardwalters** [comment]
And when I do this search (which returns a lot more results), some of them display correctly, and others don't. As here:
<img width="825" alt="screen shot 2018-05-09 at 10 49 31 pm" src="https://user-images.githubusercontent.com/11543800/39849683-9fcf3722-53db-11e8-8824-75978590aa48.png">

**Comment by wsalesky** [comment]
See this bug: https://github.com/eXist-db/exist/issues/833

**Comment by jedwardwalters** [comment]
Ah, okay. Good to know. I assume that means our hands are tied on this issue for now.

I suppose that it's at least good to know it's finding the correct matches, and only the display in the search is the problem.

**Comment by wsalesky** [comment]
There is a work around that I am trying to test, but it is challenging because we evaluate our searches dynamically. I will work on it today and see how far I can get.

**Comment by jedwardwalters** [comment]
@wsalesky I think part of the display issue is that it's still including one off instances of each word in a string in the results, even when it's only "looking for" the pairing. So, in other words, even when it's returning correct results in terms of text, it's not displaying the search results as a string. See here where you can actually see both words as part of the return results, but it's only highlighting them one at a time:

<img width="1133" alt="screen shot 2018-05-10 at 2 37 38 pm" src="https://user-images.githubusercontent.com/11543800/39887354-092fdf8a-5460-11e8-9932-38bcfc27d2fe.png">

**Comment by wsalesky** [comment]
@jedwardwalters I think the new version is an improvement. Maybe not a full solution though. Let  me know what you think.

**Comment by jedwardwalters** [comment]
@wsalesky I agree, it does seem to be working better.

**Comment by wsalesky** [comment]
@jedwardwalters Can we close this?

**Comment by jedwardwalters** [comment]
I think so. If other more specific issues arise, we can create new issues for those.
