### ISSUE TITLE
Manuscript source display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#142]
Something broke in our source display when the source is a manuscript. It's happening on both dev and production sites:

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/30.html

https://divinity-dev.app.vanderbilt.edu/exist/apps/syriac-corpus/26.html

**Comment by wsalesky** [comment]
Fixed.

**Comment by jedwardwalters** [comment]
Looks good. Thanks.
