### ISSUE TITLE
Dev site home page

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#143]
For some reason the title on the dev site home page has reverted to "Oxford-BYU Syriac Corpus" -- not a major problem at the moment. Just worth noting. 
<img width="664" alt="screen shot 2018-05-10 at 11 00 23 am" src="https://user-images.githubusercontent.com/11543800/39876634-b4ca252c-5441-11e8-9649-052af4548c64.png">

**Comment by wsalesky** [comment]
Sorry, to many versions of this running.

**Comment by jedwardwalters** [comment]
No worries. Totally  understand. I just happened to see it and wanted to make note of it. Thanks.
