### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#145]
@wsalesky Can we move the "featured work" item over to the right into that white space? (see below)
And maybe we can make "Featured Works" (note the plural works) a heading with bullet point items underneath? Then, in addition to the featured text we already have there, you can add:
https://divinity-dev.app.vanderbilt.edu/exist/apps/syriac-corpus/372.html
<img width="1434" alt="screen shot 2018-05-10 at 4 39 19 pm" src="https://user-images.githubusercontent.com/11543800/39893221-153f33e6-5471-11e8-81bc-bf1c0ab2f4dc.png">

**Comment by wsalesky** [comment]
Added

**Comment by jedwardwalters** [comment]
Looks good.
