### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#147]
@wsalesky The index page has reverted back to the old editors list  (i.e. not the split editor / editorial board)

**Comment by jedwardwalters** [comment]
On both production and dev

**Comment by wsalesky** [comment]
Oy. Fixed now.

**Comment by jedwardwalters** [comment]
Thank you. Sorry you have to keep playing whack-a-mole!

**Comment by wsalesky** [comment]
So it goes. Looks like we are pretty close to a working site.
