### ISSUE TITLE
Please make an info box for each page, possibly on the right.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#15]
We like this as a possible model:

http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0002

Above the info box:

[English Title generated from Syriaca.org @ref] - [Syriac Title from Syriaca.org @ref]

The info box should contain the following:

Stable Identifiers:
Corpus Text ID: http://SyriacCorpus.org/10
NHSL Work ID(s): http://syriaca.org/work/8512 (just /TEI/teiHeader/fileDesc/titleStmt/title[1]/@ref)

Source:
[from sourceDesc: https://github.com/srophe/syriac-corpus/blob/master/data/tei/10.xml#L61-L73]

How to Cite this Electronic Edition:
[from the How to Cite This Entry at the bottom, and remove it from the bottom, keep the collapsed function but change the expand lable to "Show full edition information..."]

also see issue #16 for the contents of How to Cite this Electronic Edition:

**Comment by wsalesky** [comment]
First run... 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=syriaccorpus.org/10

(Not yet pulling in the Syriaca.org info. )
