### ISSUE TITLE
Remove hard coded documentation

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#151]
Editorial Definitions

    Dates
    Frequently Asked Questions
    Headwords
    Language and Script Identifiers
    Place Types
    Relations
    Religious Communities
    Technical Terminology
    TEI Tag usage in Gazetteer
    Syriaca.org API Documentation
    URI Policies
    Using TEI to Catalog Syriac Manuscripts

**Comment by jedwardwalters** [comment]
Done.
