### ISSUE TITLE
Featured Works on Landing Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#154]
The URIs are encoded with the URI +.html, but it would be better to encode with just the URIs so that https://syriaccorpus.org/345 appears in the browser bar and not https://syriaccorpus.org/345.html

Featured Works

    Jacob of Serugh: On That Star Which the Magi Saw - ܥܲܠ ܟܵܘܟ݁ܒ̣ܵܐ ܗܵܘ̇ ܕܐܸܬܼܚܙܝܼ ܠܲܡܓ̣ܘܼ̈ܫܹܐ
    Exhortation of the Apostle Peter - ܡܡܠܠܐ ܕܛܘܒܢܐ ܦܬܪܘܣ ܫܠܝܚܐ ܕܥܠ ܡܪܬܝܢܘܬܐ

**Comment by wsalesky** [comment]
Fixed
