### ISSUE TITLE
Search results should highlight but NOT be in italics

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#156]
@wsalesky  I think we discussed this once, but no worries if it got away.

Because italics slant from left to right they may Syriac text look weird. So for both Syriac and Roman text search results in the search could we please just return the word in context with highlighting not italics.

See https://syriaccorpus.org/search.html?fq=;fq-Author:Philoxenos%20of%20Mabbug&q=%DC%A1%DC%A1%DC%A0%DC%A0%DC%90

**Comment by wsalesky** [comment]
Italics removed. (may require a hard refresh to see.)
