### ISSUE TITLE
Editorial titles

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#157]
@wsalesky On the landing page, in the list of editorial board members, can we make two small changes:
1) change the title after David Taylor's name from "editor-in-chief" to "Founding Editor"
2) add that same title (Founding Editor) after Kristian Heal's name

Thanks.

**Comment by jedwardwalters** [comment]
@wsalesky Actually, I went ahead and did this change myself. No need to waste your time with tiny little HTML edits! However, I do need this change to be pushed from dev server to production.

**Comment by jedwardwalters** [comment]
The other changes from dev to production server that I mentioned on a different issue are showing up, but this one still isn't. Just FYI.

**Comment by wsalesky** [comment]
Done.

**Comment by jedwardwalters** [comment]
Thanks.
