### ISSUE TITLE
Security Notice

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriac-corpus-app#159]
@wsalesky @jedwardwalters @davidamichelson I get a security notice stating "This page is trying to load scripts from unauthenticated sources." Any chance we can do something about that? Thanks.

![securitynotice](https://user-images.githubusercontent.com/4984270/40079033-11be9c32-584c-11e8-93b4-3f5173d92e9d.PNG)

**Comment by jedwardwalters** [comment]
Interesting. I haven’t had any issues in firefox, but I just opened it with Chrome and got that same warning.

**Comment by davidamichelson** [comment]
Must be certificate related. Can you document that in detail here (URL,
browser, OS) and I'll refer it to our Sys Admin.

**Comment by wsalesky** [comment]
Hi all, I think I k ow what is causing this, will try to fix in the am.
