### ISSUE TITLE
How to Cite this Electronic Edition contents

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#16]
Please revise first citation to read:

[TEI:titleStmt/author], "[TEI:titleStmt/title/[1]]", in _The Oxford-BYU Syriac Corpus [This is from TEI:titleStmt/title/[last] but not sure how we could mark it]_, last modified [revisionDesc/change[1]], publicationStmt/idno/@type="URI"].

or

Aphrahat, the Persian Sage, “Demonstration 1: On Faith,” in _The Oxford-BYU Syriac Corpus_, last modified January 1, 2017, syriaccorpus.org/1.

then revise:

Bibliography:
Aphrahat, the Persian Sage. “Demonstration 1: On Faith.” In _The Oxford-BYU Syriac Corpus_, edtied by [titlestmt/principal can we separate them with commas?] et al., last modified January 1, 2017, syriaccorpus.org/1.

then revise:
Cut:
"About this Entry
Entry Title: Demonstration 10: On Pastors"

Keep:
Publication Date: [keep this, date will be added to the TEI]

Revise:
Authorial and Editorial Responsibility: > Editorial Responsibility

Revise:
    Kristian S. Heal and David G.K. Taylor, general editors, University of Oxford
    , editor,
    , entry contributor, “Demonstration 10: On Pastors”

Cut these three lines above and instead list all editors from titlestmt/editor?

Additional Credit [keep as is for now, we need to return to this]

Current: Except otherwise noted, this page is © . Creative Commons License Creative Commons — Attribution 4.0 International — CC BY 4.0 https://creativecommons.org/licenses/by/4.0/

Revise: Except otherwise noted, this page is © Brigham Young University and released under a Creative Commons Attribution 4.0 International License — CC BY 4.0 https://creativecommons.org/licenses/by/4.0/

Revise "Hide citation" to "Hide Publication Information"

**Comment by wsalesky** [comment]
How does this look?

**Comment by wsalesky** [comment]
@davidamichelson Can I mark this as resolved?

**Comment by davidamichelson** [comment]
Yes, though we should probably visualize funder on there.

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters How would you like to see the funder visualize?

**Comment by jedwardwalters** [comment]
This may ultimately be a question for Kristian. He may have particular images or language that he wants incorporated. Maybe when we invite him to view the prototype that can be something we ask him about.

**Comment by wsalesky** [comment]
Okay. I think I will close this ticket and open a new one for funders. Thanks!
