### ISSUE TITLE
Alternate author name spellings

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#160]
@davidamichelson @dlschwartz @wsalesky 
Something to think about, but not necessarily an immediate need: Is there any way we could use the name spelling variants captured by the Syriac Biographical Dictionary in our search feature. For example, if you search for a word currently and write "Jacob of Sarug" instead of "Jacob of Serugh", you won't get any hits.

At least one solution would be to make the author box a dropdown menu. But as the corpus grows, that might become unwieldy. 

I'm open to any thoughts/suggestions here.

**Comment by davidamichelson** [comment]
This is definitely something we want and let's discuss with @wsalesky. A
temporary solution would be to import the name varients into the corpus
records for now.

**Comment by dlschwartz** [comment]
I'll put this on the agenda for Monday.

**Comment by jedwardwalters** [comment]
Closing this.
