### ISSUE TITLE
Browse by Syriac title

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#162]
@wsalesky I hadn't noticed before, but only a very small number of titles appear in the "Browse by Syriac titles" tab, despite the fact that most Corpus entries have a Syriac title. Any ideas on why that's the case?

**Comment by wsalesky** [comment]
@jedwardwalters Sorry the browse was on the wrong title. 
`tei:titleStmt/tei:title[@level="s"][@ref]` in fact, that is what the English browse is on. Is that the correct title for the English browse, or should it just be on the first title? (I'm sure there was a reason I coded it that way, but it seems like the wrong one at this point.)

**Comment by jedwardwalters** [comment]
Oh, so it’s pulling it from the NHSL work record?

Ideally those will be uniform, but there may be cases where they aren’t for various reasons. Is it possible to code the browse by the English and Syriac titles that are inside the `<title>` tag?

**Comment by wsalesky** [comment]
Is it sorting correctly on the English browse? Should we be filtering out those numbers in the title?

**Comment by jedwardwalters** [comment]
Oh, I hadn't even thought of that. Yes, We should probably filter out numbers and (if not already filtering them) also the, an, a

Also, I just noticed a curiosity in the Syriac browse. The top one that shows up under "All" starts with mem (ܡ), which is out of order, and the second one on the list doesn't even have a Syriac title (which is probably a mistake--I'll check on that). After those top two everything else seems to be in order though.

<img width="904" alt="screen shot 2018-05-17 at 10 53 29 am" src="https://user-images.githubusercontent.com/11543800/40185613-fa7bb11a-59c0-11e8-8f2a-eb77eb1cf64d.png">

**Comment by wsalesky** [comment]
@jedwardwalters the problem in the Syriac browse is in empty `tei:foreign` elements. They should not be there if they are empty. 

See: https://syriaccorpus.org/381.tei

Italics I think I have finally fixed that issue as well. Please check.

**Comment by wsalesky** [comment]
@jedwardwalters Close if it looks okay.

**Comment by jedwardwalters** [comment]
@wsalesky I made the changes to the two files that I know were wrong (because they were appearing out of order) - 364 and 381, but the results aren't showing correctly yet. Maybe those need to be pushed manually?

Once that's done we can close this out.

**Comment by wsalesky** [comment]
Fixed. https://syriaccorpus.org/browse.html?lang=syr&alpha-filter=ALL

**Comment by jedwardwalters** [comment]
Thanks.
