### ISSUE TITLE
Punctuation after source

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#163]
@wsalesky I know we've dealt with this a bit already, but I'm still not getting the period after the source (in About this digital text box) on a lot of records. It appears to be showing up on the ones that come from a manuscript: https://syriaccorpus.org/26.html

But not the ones that come from a print edition: 
https://syriaccorpus.org/27.html
https://syriaccorpus.org/1.html

**Comment by wsalesky** [comment]
@jedwardwalters The period is on the dev server. I think I may have been waiting for citation approval before moving this to production. I will go ahead and move the changes to production .

**Comment by wsalesky** [comment]
@jedwardwalters Okay, I merged changes on dev to production.

**Comment by jedwardwalters** [comment]
Excellent. That seems to have fixed it across the board. Would you still like that list? Shouldn't be too hard to manufacture.

**Comment by wsalesky** [comment]
Yes a list would be helpful, citations seem to be an ongoing source of pain for me, so when I change something I would like a check list to be able to prevent unindented consequences.
