### ISSUE TITLE
How to embed images in wiki

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#165]
@wsalesky @davidamichelson @dlschwartz Anyone know how to embed images in the github wiki? It asks for an image url when you try to insert an image (and there's no drag and drop option). Does that mean the files should live on github somewhere?

**Comment by davidamichelson** [comment]
Odd, in an issue you can drop an image. I don't know the answer, but we
could put the images here:
https://github.com/srophe/syriac-corpus-app/tree/master/resources/img

**Comment by jedwardwalters** [comment]
I think the issue with drag/drop has to do with the markdown format.

At any rate, your solution works perfectly:
https://github.com/srophe/syriac-corpus-app/wiki/How-to-View-and-Download-Texts-in-Various-Formats
