### ISSUE TITLE
Pages for Menu

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#167]
@wsalesky What's the best way for us to set up pages for the top menu? Should I just send you the text that needs to be incorporated on each page? I see that there's a mostly empty "about.html" page -- do you want me to use that as a template and just create the html pages myself? I don't mind doing that. Just let me know what's easier for you.

**Comment by wsalesky** [comment]
@jedwardwalters Add links to the menu here: 
https://github.com/srophe/syriac-corpus-app/blob/master/templates/page.html#L111

(Each menu item should be in a `<li></li>`)

To add new pages you can just use the empty about.html page as a template and add the content to that. Let me know if you run into any issues. Make sure you are using XHTML (close all your tags) or it will not load into eXist.

**Comment by jedwardwalters** [comment]
Got it. Is this the kind of thing I should do on dev first and then push over to production?

**Comment by wsalesky** [comment]
Yes, then you can check how it looks before adding it to master.
-Winona

**Comment by wsalesky** [comment]
@jedwardwalters A few things. I forgot that to get the record URI's to process correctly I had to make a 'safe list' for plain HTML pages in the controller.xql. So I had to add those pages to the list. Also, a few of your pages were malformed. What do you use to create the HTML? An editor like Oxygen should help you validate them before loading. All tags should be closed, and `&` should be escaped `&amp;` 

The pages are up now, but I think you are right they could use a little styling.  It might be nice to include some images if you have any manuscript images just to jazz up the pages a bit. If you don't I can just go through and add a little bit more formatting.

**Comment by jedwardwalters** [comment]
I’ll work on this tonight.

**Comment by wsalesky** [comment]
Okay. Let me know if you want me to do anything. The pages probably could use some larger left/right margins.

**Comment by jedwardwalters** [comment]
I started working on this tonight. Here's a test run at making the about page look better:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/about.html

I'll follow up and work on other pages tomorrow.

**Comment by wsalesky** [comment]
Looks much better. (Although you should remove that 'Place Holder' text at the bottom. )

**Comment by jedwardwalters** [comment]
I'm just playing around with copying bits of your code. Which reminds me of a question: I can't figure out how you associate different banner images with different pages. I've been scouring the srophe pages, and I just can't seem to work it out.

**Comment by wsalesky** [comment]
The different banners are included using `<xi:include href="banner.html"/>` pointing to the correct banner. The images in the banner are added via css (https://github.com/srophe/syriac-corpus-app/blob/master/resources/css/main.css#L181) You can change the class and add a new image by copying the CSS and changing the background image.

**Comment by jedwardwalters** [comment]
Ah. The CSS step is the one I was missing. Thanks.

**Comment by jedwardwalters** [comment]
Just did some further edits on about pages on dev server, but webhooks aren't picking them up.

**Comment by wsalesky** [comment]
Badly formatted pages failed, the final `<div>` was not closed. Should be okay now?

**Comment by jedwardwalters** [comment]
Sorry. De-bugging my own bad html. I'll get back to you.

**Comment by jedwardwalters** [comment]
Okay, I got my display issues worked out. I made a right-column box for links on the about page, but I can’t figure out how to populate it. I made an “about-menu.html”—mimicking what I saw on syriaca.org—but that didn’t do the trick. Any suggestions?

**Comment by wsalesky** [comment]
You did everything right. the about-menu.html did not load to dev. Not sure why, looks okay to me. I added it.

**Comment by jedwardwalters** [comment]
Yay, I got it right! Okay, so, to wrap this issue up on my end, I need to fix the other html pages I created.

However, the history.html and contact-us.html pages aren't loading at all. What needs to happen there?

**Comment by jedwardwalters** [comment]
Those two pages are showing up as well-formed in Oxygen, and I just made a few tweaks to all of the html pages I created. I can see the About and Project Team pages fine (I think they're done). Still can't see History or Contact.

**Comment by wsalesky** [comment]
I will take look when I get home

**Comment by jedwardwalters** [comment]
Thank you. Sorry this caused so many issues. I think it's nearly done though. I'm also slogging through all of the documentation today.

**Comment by davidamichelson** [comment]
@jedwardwalters I would like to suggest that the wiki page "Ways to Contribute" also be included in this about menu as a way to encourage contributions.

**Comment by jedwardwalters** [comment]
@davidamichelson I was thinking about that. Here are our options:
1) put links to "Ways to Contribute" and "Proposal Guidelines" from the wiki in the drop down menu
or
2) I'll create that submissions.html page to be included in the menu with some of that info and then links to the two wiki pages
Thoughts?

**Comment by davidamichelson** [comment]
Great, proposal guidelines is perhaps more direct, since the other might be
confused as a solicitation for donations.

**Comment by davidamichelson** [comment]
I don't know what I mean actually. Just wanted to point out that contribute
was ambiguous. I'll let you decide what is best and even contribute is fine.

**Comment by jedwardwalters** [comment]
Everything looks great!
