### ISSUE TITLE
HTML Pages vs. Wiki

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#168]
@davidamichelson Are there any information pages that should be hard-coded as HTML pages? Or should everything be in the Wiki?

For some reason, I had it in my mind that some thing (like the "about the project" page, or the "history of the project" page we've been working on, "project team", etc.) would be written as HTML pages. But now I'm wondering if there's any reason those shouldn't just be in the wiki?

I looked over at the Syriaca app, and some of these pages are coded in HTML. So I'm just trying to figure out what the distinction is.

**Comment by davidamichelson** [comment]
Yeah, the same thought had crossed my mind. One issue would be the styling
as HTML is more flexible, but can you insert HTML into a github wiki?
