### ISSUE TITLE
Caption for Header Image on Landing Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#169]
Needs a white space after colon between Credit: Image
Current "Photo Credit:Image Colchester 1932.228 f. 4b"
Revised "Photo Credit: Image Colchester 1932.228 f. 4b"

**Comment by jedwardwalters** [comment]
@wsalesky I just adjusted this on the banner.html on the master branch, but the change hasn't showed up yet (even after hard refresh).

**Comment by davidamichelson** [comment]
This still seems to be an issue on the dev server at least.

**Comment by davidamichelson** [comment]
@wsalesky FYI

**Comment by wsalesky** [comment]
Ah, yes that would be the issue. I need to teach you git cherry-pick... For moving just one change to another branch.

**Comment by jedwardwalters** [comment]
That might come in handy!

**Comment by wsalesky** [comment]
@jedwardwalters closing as a stale issue.
