### ISSUE TITLE
Error on Title

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#18]
Currently reads "Title app:get-srophe-title()" in the right side bar.

**Comment by davidamichelson** [comment]
@jedwardwalters @nathangibson We need to push the approx 25 NHSL records to production for Aphrahat so we can use them for the corpus API, would that be fine to do in a silent way please?

**Comment by jedwardwalters** [comment]
Okay, that sounds good to me. Let me know if I need to do anything.

**Comment by nathangibson** [comment]
OK, I will try to do this soon.

**Comment by jedwardwalters** [comment]
I think this is resolved now that you've published the NHSL records, right @nathangibson?

**Comment by nathangibson** [comment]
Not sure. These are on dev right now. Dave originally said these have to go to production to fix the error, but I don't see where the original error is.

**Comment by wsalesky** [comment]
They need to go to production in order for the script to grab the title.

**Comment by nathangibson** [comment]
OK, I'll move them now. @jedwardwalters is working on getting Syriac titles in, so I can copy them over again once he does that.

**Comment by nathangibson** [comment]
OK, @wsalesky I've copied them to master, but I can't bring them up on the server. When I look under webhooks "recent deliveries" it looks successful, but they just pull up a 404 when I try to go to e.g. http://syriaca.org/work/8501.

**Comment by jedwardwalters** [comment]
@nathangibson I was just about to start working on this. So should I still edit the files on the dev server?

**Comment by nathangibson** [comment]
Yes, please. I'll copy them over again when you're done. But please note that @wsalesky will be working on the dev server for the next hour. I think you're fine if you're just using github and not trying to load pages at http://wwwb.library.vanderbilt.edu/.

**Comment by jedwardwalters** [comment]
Okay. Will do.

**Comment by wsalesky** [comment]
@nathangibson Looks like most of the NHSL records failed to upload. You can see this by clicking on the 'response' tab. It shows green because some of the uploads were successful. I will try to upload them manually.

**Comment by nathangibson** [comment]
Thanks.

**Comment by wsalesky** [comment]
@nathangibson Okay, I added them.

**Comment by wsalesky** [comment]
@nathangibson errr, now that I think about it having these on the production server will cause some issues (they will show up in search and browse). I think perhaps we should remove them and I can rethink how the corpus and syriaca.org will share data. Sorry for the extra work!

**Comment by nathangibson** [comment]
No problem. Shall I just revert the commits?

**Comment by wsalesky** [comment]
Yes. Sorry about that. Still trying to work out how everything will talk to each other.

**Comment by nathangibson** [comment]
OK, I've reverted. (I also accidentally reverted an earlier revert, so now the commit history looks crazy, but I think it should be correct!)

**Comment by wsalesky** [comment]
Will self resolve once the SPARQL module is working on dev.
