### ISSUE TITLE
(Ps.) Clement works not expanding

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriac-corpus-app#187]
@wsalesky @jedwardwalters In browse, https://syriaccorpus.org/browse.html?lang=&alpha-filter=ALL&view=author, the works of Clement do not expand when selecting the "+" by the name.

**Comment by jedwardwalters** [comment]
I can also just take out the (Ps.-) in the name if that's easier. I debated including it in the first place.

**Comment by wsalesky** [comment]
@dlschwartz @jedwardwalters I fixed this. It now opens and closes and sorts correctly.

**Comment by jedwardwalters** [comment]
Excellent. Thank you. And thanks for catching that, @dlschwartz!
