### ISSUE TITLE
Status and Type Documentation

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#188]
@wsalesky I don't remember where we discussed this, but on a previous issue we discussed having a small question mark beside "Status" and "Type of Text" in the right hand box that would link to the documentation for those pages. Here are the links:

Status: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/documentation/wiki.html?wiki-page=/Status-of-Texts-in-the-Digital-Syriac-Corpus&wiki-uri=https://github.com/srophe/syriac-corpus/wiki

Type: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/documentation/wiki.html?wiki-page=/Types-of-Text-in-the-Digital-Syriac-Corpus&wiki-uri=https://github.com/srophe/syriac-corpus/wiki

**Comment by wsalesky** [comment]
@jedwardwalters How is this? If you like the placement I will merge into master. 

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/1

**Comment by jedwardwalters** [comment]
Thanks, @davidamichelson. I'll get this adjusted.

**Comment by jedwardwalters** [comment]
Done. Thanks for the help clarifying these things.
