### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#189]
@davidamichelson @dlschwartz I'd be happy to have any feedback on the Documentation Wiki pages. 

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/documentation/index.html

I've edited everything except "The Syriaca.org Web Application" because we said in our meeting last week that @wsalesky would edit that one.

**Comment by jedwardwalters** [comment]
Note: per our discussion on Monday: I'm still wondering whether we should have a "Contributing to the Corpus" static html page, particularly for the reason of having a nice clean URL like syriaccorpus.org/submissions

I wouldn't even have to remove those pages (Ways to Contribute, Proposal Guidelines) from the wiki--I could link to them from the static page.

Any thoughts on this?

**Comment by davidamichelson** [comment]
Go for it!

**Comment by wsalesky** [comment]
@jedwardwalters I updated the "The Syriaca.org Web Application" wiki page.

**Comment by jedwardwalters** [comment]
Thanks, @wsalesky. I probably won't get to the submissions.html page until after NAPS. 

I think we are close, though, on being able to have the other menu pages and documentation pushed to production server. One issue (now that I can see the history page): The footnotes at the bottom of the page need some formatting. I wasn't sure how best to code those in html to make it easy on your end to style them. Primarily the issue is that all the footnotes show up in a single paragraph--not broken out with each note on a line.

Let me know if there are some html adjustments I need to make to fix those.

**Comment by wsalesky** [comment]
@jedwardwalters How does this look? I just added div's to make new lines. (Although I suppose you could just use a p or br tag)

**Comment by jedwardwalters** [comment]
Thanks. I think I'll try to add some padding on the left and right margins.

**Comment by jedwardwalters** [comment]
Before I mess with anything, would the best way to add padding be to add a p tag with class="indent"? If so, would that go around the `<span>` or inside it here:
https://github.com/srophe/syriac-corpus-app/blob/dev/history.html#L33

**Comment by wsalesky** [comment]
You can add an additional class to the container.  `<div class="container">` becomes  `<div class="container indent">`

**Comment by jedwardwalters** [comment]
Okay, I've done that now. But I didn't see any change to the format after a hard refresh.

**Comment by wsalesky** [comment]
Sorry I had the file open on the server, it locked it so  webhooks failed. Try now.

**Comment by jedwardwalters** [comment]
I want them to look like the footnotes on this page: http://syriaca.org/saints/intro.html

So, can I just re-do the notes using the format found here:
https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/saints/intro.html#L49
and here:
https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/saints/intro.html#L1034

**Comment by wsalesky** [comment]
Yes, use the same format and the CSS should make it look the same.

**Comment by davidamichelson** [comment]
@jedwardwalters It looks great to me!

**Comment by jedwardwalters** [comment]
@wsalesky I just added the re-formatted footnotes on history.html on dev, but those changes aren't showing up yet.

**Comment by wsalesky** [comment]
It is there now, the font is larger, I think you can add class 'small' if you want to make it display smaller. I'm sending some instructions for troubleshooting, and resending failed webhook requests, via email.

**Comment by jedwardwalters** [comment]
Thanks. I think I will make it a bit smaller. And thanks for instructions. I hate bothering you every time we need a web hook check!

**Comment by jedwardwalters** [comment]
@wsalesky One thing more, and I think we are ready to push the about pages and documentation wikis to the production server:

I created the submissions.html page. It shows up in the drop down menu and the about page menus, but the link doesn't actually load the page yet. I was having this same problem with history and contact-us, but that got resolved.

**Comment by davidamichelson** [comment]
Jamey this looks really great, you should be proud.

**Comment by jedwardwalters** [comment]
Thanks, Dave, for all your help.

And thank you, Winona for all your hard work this week! If you don’t get around to pushing the documentation, etc. to production tonight, it’s not a crisis!

**Comment by wsalesky** [comment]
@jedwardwalters I have the 404 working and the submissions back up. I will move everything over to production tonight.

**Comment by jedwardwalters** [comment]
Thanks. I just spied an issue with my html formatting on submissions now that it's up. I'll fix that right now.

Also, I'm working from a train en route to Chicago!

**Comment by wsalesky** [comment]
Whee! Okay, I'm done until after the kids go to bed, so I will check back
in around 9 EST.
-Winona

**Comment by davidamichelson** [comment]
@jedwardwalters I noticed an issue with the mention of PDF in the submission guidelines. I am not sure it should be preferred over word processor. Let's discuss later.

**Comment by jedwardwalters** [comment]
Yeah, you're right. That shouldn't be there. I know what I was thinking when I put it, but it doesn't actually make sense. I'll just remove the PDF line altogether.

**Comment by jedwardwalters** [comment]
Closing this one down too.
