### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#204]
@wsalesky I know we fixed this once, but we aren't getting a proper 404 page when expected. It's just that blank white page that says "Easy does it!"

**Comment by davidamichelson** [comment]
Also just for fun can we add the syriac text of Ecclesiastes 12:12 too!

**Comment by jedwardwalters** [comment]
I went ahead and added the Syriac text.

**Comment by wsalesky** [comment]
Updated.

**Comment by jedwardwalters** [comment]
Just checked and it works fine.
