### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#213]
@wsalesky I just did a pull request with some edits to the history.html page, but the webhook failed (https://github.com/srophe/syriac-corpus-app/commit/4a7bd4499cad3df80ab016b2f936147ec05aedf9). 

I looked at the webhook failure message, and it said "SSL peer certificate or SSH remote key was not OK" -- I'm not sure what that means.

**Comment by jedwardwalters** [comment]
This was on master/production server, btw.

**Comment by wsalesky** [comment]
@jedwardwalters 
I changed the webhook to point to the production 'pretty url' : https://syriaccorpus.org/

Now we get this error. 
`     <message>Failed to update resource /db/apps/syriac-corpus/history.html: java:org.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (32,1031) : The reference to entity "wiki-uri" must end with the ';' delimiter. XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (32,1031) : The reference to entity "wiki-uri" must end with the ';' delimiter.</message>
`

`&` always need to be escaped in xml. so `&` should be encoded as `&amp;` in the url to the wiki article.

**Comment by jedwardwalters** [comment]
Thank you. I fixed it and the webhook worked.
