### ISSUE TITLE
Corpus texts not displaying

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#219]
@wsalesky The corpus home page is loading, but I'm getting an error (see below) on any text display:
<img width="1185" alt="screen shot 2018-10-03 at 9 52 09 am" src="https://user-images.githubusercontent.com/11543800/46414996-5679ac80-c6f2-11e8-9731-7286a4cdb514.png">

**Comment by wsalesky** [comment]
@jedwardwalters Contacted server person, waiting to hear back.

**Comment by jedwardwalters** [comment]
Thanks!

**Comment by wsalesky** [comment]
@jedwardwalters Back up. Sorry about the delay. eXist seems to be having some memory issues. We are working on it.

**Comment by jedwardwalters** [comment]
Thank you!
