### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#225]
@wsalesky Something is off with the search function on the Corpus. It's not actually returning any results for me. For instance, I just searched the word ܩܢܘܡܐ, and the result list that shows up appears to just be everything in the corpus, but there are no actual matches for the word listed. (And I know for sure that that word is not in every single text.)

Search results here:
https://syriaccorpus.org/search.html?fq=;fq-&keyword=%DC%A9%DC%A2%DC%98%DC%A1%DC%90

**Comment by wsalesky** [comment]
Fixed. Make sure to do a hard refresh. (This was a problem in the navbar search box only. So to check, do a hard refresh, and do a search from the navbar. )

**Comment by jedwardwalters** [comment]
Thanks. I refreshed and it's working as expected now!
