### ISSUE TITLE
Character display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#227]
@wsalesky Something is wrong with the character display on the homepage of the Corpus. See image below:
<img width="1440" alt="screen shot 2019-02-16 at 9 33 05 pm" src="https://user-images.githubusercontent.com/11543800/52907608-bf416b80-3232-11e9-8036-fa3fe471edb2.png">

**Comment by wsalesky** [comment]
There is a serialization error in eXist-db 3.5.0, this can be solved by uploading the files via the dashboard (which is what I have done). I reported the issue to eXist and hope to see a fix in the next few months.

**Comment by jedwardwalters** [comment]
Sorry to have to ask, but what do you mean by "uploading the files via the dashboard"?

**Comment by jedwardwalters** [comment]
@wsalesky FYI the weird characters are still showing up on the 404 page:
https://syriaccorpus.org/404.html

Then we can close this issue.

**Comment by wsalesky** [comment]
Fixed.

**Comment by jedwardwalters** [comment]
Thanks.
