### ISSUE TITLE
Webhook (dev)

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#228]
@wsalesky Sorry, one more for tonight: I'm testing a new text on the dev branch, and the webhook failed.

**Comment by wsalesky** [comment]
Sorry, which commit # failed?

**Comment by jedwardwalters** [comment]
The initial one was [`df8e5b5`](/srophe/syriac-corpus/commit/df8e5b51b51910fe16e9ba2c7f23551ffa07b394) on the dev site, but now there's also another failed on one the production site: [`f92cdb4`](/srophe/syriac-corpus/commit/f92cdb4a8e3446fb0ac179b1c073697bed304dc8)

**Comment by jedwardwalters** [comment]
Also, FYI: the corpus has been on an up/down roller coaster today.

**Comment by wsalesky** [comment]
Interesting. I will take a look tonight, see if there is anything in the log files. 

The webhooks claim to have worked for 390.xml? Are you not seeing the changes? 

<img width="797" alt="screen shot 2019-02-17 at 2 43 41 pm" src="https://user-images.githubusercontent.com/1168206/52918193-776a2500-32c2-11e9-9a5f-93023ecee6f3.png">

**Comment by jedwardwalters** [comment]
Oh, maybe it was this one that failed: [`bc02517`](/srophe/syriac-corpus/commit/bc02517cbf913bc28f22e6a28747511190173ec9)

I forgot to change the URI in the initial commit, then I went back and changed it.

**Comment by jedwardwalters** [comment]
@wsalesky I'm just following up here on two different webhook things:

1) On the DEV server: text 390 is still not displaying. I think the commit that failed is in the above comment (https://github.com/srophe/syriac-corpus/commit/bc02517cbf913bc28f22e6a28747511190173ec9

2) On the production server: text 391 is not displaying (this is the new one I was trying to add the other day when the characters went wonky). Here's the commit: https://github.com/srophe/syriac-corpus/commit/f92cdb4a8e3446fb0ac179b1c073697bed304dc8

Note: these are not high priority things at the moment. If you're mired down in other things, I understand. I just wanted to circle back to make sure this was all communicated.

**Comment by wsalesky** [comment]
Okay, 390 is on the dev server. Not sure what the problem was but I just rand the webhook for that commit again. 

And 391 is up on the production site, but I had to use the collection browser due to the character encoding issues.
