### ISSUE TITLE
Proximity Search

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#229]
Hi  @wsalesky, I am SO sorry to have to keep bugging you with things, but it seems like the proximity search is not working. I've tested several pairs that I know should return results (such as "ܢܦܫܐ+ܦܓܪܐ" in a 10 word radius), and it's returning no results:
https://syriaccorpus.org/search.html?q=%22%DC%A2%DC%A6%DC%AB%DC%90%2B%DC%A6%DC%93%DC%AA%DC%90%22&keywordProximity=10&author=&title=&fq=&section=&corpus-uri=&syriaca-uri=&text-id=

It's not working on production or dev sites.

**Comment by wsalesky** [comment]
@jedwardwalters no problem, we will get it ironed out. due to snow day issues I'm running a little behind but will try to get to all of these today.

**Comment by wsalesky** [comment]
Looks like the problem is when you use quotes, as the proximity operator function will wrap the search terms in quotes automatically. I guess I should have it check for quotes before adding them. 

See this working example: 
https://syriaccorpus.org/search.html?q=%DC%A2%DC%A6%DC%AB%DC%90+%DC%A6%DC%93%DC%AA%DC%90&keywordProximity=10&author=&title=&fq=&section=&corpus-uri=&syriaca-uri=&text-id=

**Comment by jedwardwalters** [comment]
I was just trying to view your results, but it looks like the server isn’t responding. Home page isn’t loading either.

**Comment by wsalesky** [comment]
@jedwardwalters try now?

**Comment by jedwardwalters** [comment]
I just got back from teaching, and the site is down. According to the Uptime Robot monitor I have set up, it's only been down for a few minutes, but it's been going in and out quite a bit over the last few days.

**Comment by jedwardwalters** [comment]
This is as of 2:40 pm EST. As you can see, it's gone out several times today, but never stays down long:
![screen shot 2019-02-21 at 2 40 28 pm](https://user-images.githubusercontent.com/11543800/53196707-a7793700-35e6-11e9-9394-8c435230dda9.png)

**Comment by jedwardwalters** [comment]
Sorry for the delay. I tried your search result above and tested my own. From what I can tell, the results aren't actually "proximity" results, they're just showing all the instances where either word occurs in the text. See example below:
https://syriaccorpus.org/search.html?q=%DC%A2%DC%A6%DC%AB%DC%90%2B%DC%A6%DC%93%DC%AA%DC%90&keywordProximity=10&author=&title=&fq=&section=&corpus-uri=&syriaca-uri=&text-id=
<img width="650" alt="screen shot 2019-02-22 at 12 08 40 pm" src="https://user-images.githubusercontent.com/11543800/53258531-d7821200-369a-11e9-8b0a-f6f0e6fb68bd.png">

**Comment by wsalesky** [comment]
Huh, if I change the proximity operator the results change. I think I need a better test case. I'm going to try to put together some full text English documents to test it on. I will get back to you

**Comment by jedwardwalters** [comment]
Ah okay. I didn’t try changing the number. I’ll play around a bit more too.

**Comment by jedwardwalters** [comment]
I'm tempted to say that the proximity search is working because most of the text results that show up do have at least one pairing of the two words, but the search results also appear to be showing every time either word appears within that same text.

However, that being said, there are also exceptions that I can't seem to figure out. If you look in the image I posted above, the results under "Against the Manichaeans" do not appear to have any results where the two words are actually close to each other.

**Comment by wsalesky** [comment]
I think the KWIC function in eXist-db is broken for proximity searches. I
suspect this is a manifestation of the issue.
https://github.com/eXist-db/exist/issues/833 I will see if there has been
any movement on it.

**Comment by jedwardwalters** [comment]
@wsalesky I'm pinging this issue again to see if there have been any developments. I'm writing an article right now about the Corpus, and I'd love to mention the proximity search capability, but I don't want to include it if we aren't sure it's going to be working soon.

**Comment by wsalesky** [comment]
@jedwardwalters The proximity search does work, the hit highlighting for proximity and phrase matching searches does not work correctly, this bug is still an open bug in eXist, I have tested it in the latest 4.x.x branch and the 5.x.x branch and it is still an issue.

**Comment by wsalesky** [comment]
I can probably write a regex that only shows matches with the specified proximity, but it might take me a few hours, to get working. Is this something you would want me to try as a patch?

**Comment by jedwardwalters** [comment]
Ah okay. Well I would never ask you to do that for free, so let me ask if we have any funds available for that.

**Comment by jedwardwalters** [comment]
I thought that's how it was set up initially, so that's why I thought there was an error in the results.

**Comment by wsalesky** [comment]
Okay, well let me know what you want to do.

**Comment by wsalesky** [comment]
Solution created and tested on e-gedsh (since it was easier for me to read the results). 

See: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/search.html?q=aphrahat+sage&keywordProximity=10&author=&placeName=&persName=&bibl=&uri=

I will be moving it to the corpus dev site today so you can test the Syriac, it should behave the same though.

**Comment by wsalesky** [comment]
@jedwardwalters As with many things Syriac this is more complicated then the English version: 
See:
<img width="1414" alt="Screen Shot 2019-09-19 at 11 20 28 AM" src="https://user-images.githubusercontent.com/1168206/65257655-88387e80-dacf-11e9-94dd-37630ab850a6.png">


Records that have no hits showing  (#3) up, are returned correctly by Lucene, but the Syriac words have an additional prefix or suffix (not sure the correct terminology here) so the regex does not grab them, as it works on word boundaries. I can try a 'contains' rather than word boundary but you may end up with some odd false positives that way as well.  Thoughts?

**Comment by jedwardwalters** [comment]
I'm trying to re-create your search, but I'm not getting any actual results listed under the titles:
<img width="1424" alt="Screen Shot 2019-09-19 at 12 43 42 PM" src="https://user-images.githubusercontent.com/11543800/65263760-3dbcff00-dadb-11e9-9c4a-01d9407b40ff.png">

**Comment by wsalesky** [comment]
@jedwardwalters I have not moved it to production yet, and the dev server is an older version of eXist and is behaving oddly. This is my local instance. Would you like me to move the changes over so you can play with it?

**Comment by jedwardwalters** [comment]
Ah okay. Sure, we can try it on the production server for testing.

Question: can proximity search be used in conjunction with the other wildcard searches? So, if you searched for a three letter root with an asterisk as part of a proximity search, would that work? (i.e. searching for ܦܓܪ* instead of ܦܓܪܐ)

**Comment by wsalesky** [comment]
Okay try on production: 

https://syriaccorpus.org/search.html?q=%DC%A2%DC%A6%DC%AB%DC%90%20%DC%A6%DC%93%DC%AA%DC%90&keywordProximity=2

Also, you can not do wild card searches in phrase searching, which is how the proximity search works. https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Term%20Modifiers

**Comment by jedwardwalters** [comment]
Hmm I think I broke it. Your linked search came up fine and mostly gives expected results (except for the "blank" results you mentioned earlier). But when I tried to do a different search I got a proxy error.

**Comment by jedwardwalters** [comment]
Okay, I tested and got some good results. I did the two words we've been testing ܢܦܫܐ and ܦܓܪܐ with a 5 word proximity. The results it shows under the first text in the image below ("on the soul") are good:
<img width="1424" alt="Screen Shot 2019-09-20 at 11 26 24 AM" src="https://user-images.githubusercontent.com/11543800/65339672-94d5d900-db9a-11e9-8274-cf195beb13ed.png">

The second item in the list doesn't list any results:
<img width="664" alt="Screen Shot 2019-09-20 at 11 31 37 AM" src="https://user-images.githubusercontent.com/11543800/65339710-acad5d00-db9a-11e9-8cd9-42ce441cf543.png">

So given the previous discussion, it makes sense to me why this particular result from that text isn't getting caught (because there's a prefix on one of the):
<img width="685" alt="Screen Shot 2019-09-20 at 11 31 10 AM" src="https://user-images.githubusercontent.com/11543800/65339789-cd75b280-db9a-11e9-92f2-39c1314ddcd2.png">

However, there's one further down the page that I think should be showing up in the results:
<img width="683" alt="Screen Shot 2019-09-20 at 11 27 55 AM" src="https://user-images.githubusercontent.com/11543800/65339831-e2524600-db9a-11e9-9f89-76bab91ea347.png">

Any thoughts? Do you think the "contains" rather than the boundary would work better?

**Comment by wsalesky** [comment]
So the problem is for that second example is the word order. Proximity searching works on a  phrase search, and how close the two words are in the phrase, that means word order matters. It looks like the second example the word order is reversed is that correct?

**Comment by jedwardwalters** [comment]
OH, I didn't realize word order would matter. That makes sense.

**Comment by wsalesky** [comment]
I will try it with contains, see if that helps.

**Comment by jedwardwalters** [comment]
Okay. Sounds good. I think it may just be worth customizing the "search help" content for the Corpus. I doubt that would be much trouble, and I can probably do it myself.

**Comment by wsalesky** [comment]
Contains does not work. I think just documenting the results would be best.

**Comment by jedwardwalters** [comment]
Okay. Thanks for trying!

So, otherwise, are we done with this feature enhancement since it's already live on the production server?

**Comment by wsalesky** [comment]
Yes!

**Comment by jedwardwalters** [comment]
Thank you for your work!
