### ISSUE TITLE
Slider bar

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#230]
On the advanced search page, the slider bar is showing up at the bottom:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html

**Comment by wsalesky** [comment]
@jedwardwalters Fixed! Let me know when you want me to move it to production.

**Comment by jedwardwalters** [comment]
I think we can go ahead! I'm not going to announce it yet, primarily because not all texts have dates yet, but also because it will be nice to have some time to make sure it's working correctly before we launch.

Quick question: is there an easy way to move all the date information that I added to the files on the dev server for testing over to the files on the production server?

**Comment by wsalesky** [comment]
Yes, merge them into master. If the webhooks fail I will upload them manually. Let me know how it goes.

**Comment by jedwardwalters** [comment]
I think we still have the webhook for production server turned off. I can merge them on github and then upload them manually.

**Comment by wsalesky** [comment]
Okay. Let me know if you have any problems.

**Comment by wsalesky** [comment]
@jedwardwalters code is live. Let me know if you run into any issues.

**Comment by jedwardwalters** [comment]
Thanks! I'll try to get to this today or tomorrow.

**Comment by wsalesky** [comment]
@jedwardwalters Side note, there are a lot of stale branches on this repository. As a general workflow good practice I suggest deleting a branch right after you merge it into master.

**Comment by jedwardwalters** [comment]
Yes, thanks for that reminder!

**Comment by jedwardwalters** [comment]
@wsalesky Is git cherry pick the best way to do the merge on here?

**Comment by wsalesky** [comment]
It depends. If you want to merge all of your dev data to master then just use merge. If you don't want all the data then you may need to use cherry pick, which is fine if all the changes are in one commit. If they are in multiple commits it will be faster to create a new branch, add all your changed data and then merge it into master.

**Comment by jedwardwalters** [comment]
Ah okay. I looked at just merging dev into master but it looks like there are other commits that would merge as well, and I didn't want to mess anything up. And yes I think all the changes are in one commit.

Maybe I'm missing something though, so let me ask it this way: Is there a way through github to isolate a single branch/commit that has already been merged into dev and then just merge that single commit into master? If there is a way to do that, it's not obvious to me.

**Comment by wsalesky** [comment]
To be clear you made your changes on a branch and then merged that branch into dev? And now you want to merge it into master? 

If you still have that branch you can merge it into master, although it is usually a good idea to merge master into your branch first (in case there are changes in master that are not in dev) and then merged the updated branch into master. This keeps any bad merge conflicts on your branch and out of master.

**Comment by jedwardwalters** [comment]
Okay, I got it done. The files are merged on Github and I uploaded them manually through the dashboard.

I just tested the search, and everything seems to be working as expected. As I continue to update the other texts with date data, I'll let you know if I come across anything else.

Thanks so much!
