### ISSUE TITLE
Browse and search return 0 results

### ISSUE THREAD

**Issue by nathangibson** [srophe/syriac-corpus-app#238]
I hope you don't mind my filing an issue for something I'm not actively involved in ... 

Browse https://syriaccorpus.org/browse.html and search (e.g., https://syriaccorpus.org/search.html?q=jacob) return 0 results. However texts still load if requested by URI. 

I didn't have this issue a month or two ago, last time I was browsing through the corpus.

**Comment by wsalesky** [comment]
@nathangibson Thanks! Looks like this instance was updated recently and need a re-index. Working now.

**Comment by nathangibson** [comment]
Sadly this is back
