### ISSUE TITLE
Footnote display on a <head>

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#239]
@wsalesky There's an issue with how footnote numbers get displayed when they're on a title that gets marked as a `<head>`. 

If you include the `<note>` tag within the `<head>` tag, then the text of the footnote shows up in the Table of Contents. That's easy to fix: I just move the note outside the `<head>` tag. But that creates a different problem: it makes the footnote number in the displayed text show up on a new line after the header title. See images below (the footnote number 23 is stranded on its own line):
<img width="799" alt="Screen Shot 2021-02-23 at 9 43 34 PM" src="https://user-images.githubusercontent.com/11543800/108939998-a1c4ea80-7620-11eb-95ce-5189f24a44e9.png">
<img width="662" alt="Screen Shot 2021-02-23 at 9 43 51 PM" src="https://user-images.githubusercontent.com/11543800/108939999-a1c4ea80-7620-11eb-9b33-b24854b1fed2.png">

**Comment by jedwardwalters** [comment]
By the way, this is in this review: https://hugoye.bethmardutho.org/article/hv24n1prpalmer

**Comment by jedwardwalters** [comment]
Another issue in the same review: The period at the end of a Syriac quote paragraph is showing up on the right side of the final line, but it should be at the end on the left side. Any thoughts on how to fix this?
<img width="662" alt="Screen Shot 2021-02-23 at 10 07 26 PM" src="https://user-images.githubusercontent.com/11543800/108941873-d8503480-7623-11eb-908a-96ebbc8ad6e2.png">

**Comment by wsalesky** [comment]
@jedwardwalters Just to clarify, this is a problem on the Corpus, not Hugoye? Can you link to an example record?

**Comment by jedwardwalters** [comment]
Oh gosh, no, it's on Hugoye. I'm sorry! I put it on the wrong repo. I'll move these issues to the Hugoye one.

Sorry!
