### ISSUE TITLE
Mismatch in text display

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#246]
Then I noticed that the text displayed in html and the tei behind it don't seem to be the same thing. The text in the tei:div @type="rubric" matches the first paragraph in the html but the text in the first tei:p does not match the first paragraph in the html. 

Example: 229

**Comment by davidamichelson** [comment]
For what it is worth Safari and Firefox (on Mac and PC) both render fine.

Chrome on PC and Mac both have the same issue. Chrome starts displaying the text at ```<pb ed="http://syriaca.org/manuscript/2295" n="115"/>``` with the phrase ```ܚܘܼܣܝܐ: ܘܙܒܢ̈ܝܼܢ ܣܓ̈ܝܐܢ ܡܫܬܼܚܠܦ ܗܼܘܐ: ܘܐܝܟ ܗܿܘ```

**Comment by davidamichelson** [comment]
When you copy the first line in Chrome the text that it gives you is actually three lines from the start of the TEI:
```ܣܘܼܟ̈ܠܐ܀ ܐܦ ܗܕܐ ܕܥ܆ ܕܐܝܠܝܢ ܕܒܗܢܐ ܟܬܒܐ ܪ̈ܫܝܼܡܢ: ܫܘܼܡܠܝܐ```

**Comment by davidamichelson** [comment]
FYI, this error only occurs in some files, such as files 228, 229, 230 have display problems, but record 20 displays fine.
Also, if you watch closely in Chrome, when it first loads the page for 228 it displays fine but then switches to the incorrect.

**Comment by davidamichelson** [comment]
One more note, in the problem files (229 and 230) turning on show page break on the right fixes the display problem.

**Comment by davidamichelson** [comment]
@wsalesky I think the page break rendering is the source of the problem. We can discuss tomorrow.

**Comment by wsalesky** [comment]
@wsalesky Note to self, this is caused by the pb toggle function. Currently testing different methods for dealing with it.

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz Can you take a look. I think I fixed it but need confirmation form Syriac readers. Thanks.

**Comment by jedwardwalters** [comment]
Thanks, Winona. I just tested in firefox and chrome, and everything looks okay. BUT, when I click to toggle the page break in Chrome, it causes the page to become unresponsive. This happened twice. on 229 and 230.

Jamey

**Comment by wsalesky** [comment]
Okay, thanks for the update I will make a new bug for the page break toggle.
