### ISSUE TITLE
Visualize funder information/logo

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#26]
Need some feedback on how this should be displayed.

**Comment by jedwardwalters** [comment]
Two things (ultimately):

1) on landing page, there should be logos for funding

2) on each page, along with editorial information in the right hand "How to Cite" box, it would be great to include a "Funder" section to be taken from <funder> in <titleStmt>

**Comment by wsalesky** [comment]
Added it to the citation for each record. Will list any funders in the `titleStmt/funder`. Will add logos to landing page when I have them. 

We also need some content for that page.

**Comment by jedwardwalters** [comment]
Great, thanks. I'll make an issue for myself to work on content for the landing page. So we can go ahead and close this and I'll make a note about funding logos in that issue.

**Comment by wsalesky** [comment]
Sounds good.
