### ISSUE TITLE
Search options

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#27]
@jedwardwalters  @dlschwartz 
Current search is just using the Syriaca.org default search options. We will need to make a list of fields that should be searched and limits/filters should be enabled.

**Comment by dlschwartz** [comment]
I think we discussed this in a recent meeting. Can we close this?

**Comment by jedwardwalters** [comment]
@dlschwartz It has been sitting on my to-do list to communicate to Winona what we talked about at our recent meeting. So this is as good an excuse as any to cross it off!

@wsalesky For the search options, we discussed having the following options:
1) Author:
/TEI/teiHeader/fileDesc/titleStmt/author

2) Title:
/TEI/text/body/div1/head/title

3) Section number
/TEI/text/body/div1/div2/head

4) Corpus URI
/TEI/teiHeader/fileDesc/publicationStmt/idno

5) Syriaca URI
/TEI/teiHeader/fileDesc/titleStmt/title/@ref

6) Text ID Number (in other words, just the URI number without the rest of the URI address)
(I'm not sure what to put for an XPath here)

And the Title and Author searches should support both English and Syriac.

**Comment by wsalesky** [comment]
I added these fields. Please test and let me know if you find any bugs or unexpected behaviors. 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html

Thanks!

**Comment by jedwardwalters** [comment]
One thing I noticed here: the section number box doesn't actually limit the results. See attached photos--with that search option, I should only see the line where the desired keyword (ܚܒܝܒܝ) appears in section 5. But it shows me all the occurrences of the word in that work. So, we don't want it to capture the 5 as a search result, but we want the keyword search restricted to the section number. (This won't apply to all texts the same way, I suppose. But it will be a nice feature for texts that have section numbers.)
![search](https://cloud.githubusercontent.com/assets/11543800/23218173/8cf4df10-f8e9-11e6-9672-50f44046b1cd.jpg)
![results](https://cloud.githubusercontent.com/assets/11543800/23218179/914ab008-f8e9-11e6-899a-4d38bb1917a0.jpg)

**Comment by wsalesky** [comment]
@jedwardwalters Finally getting around to some of these teaks. I have added a filter to limit keyword in context results to section # if present in search. 
Example: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%9A%DC%92%DC%9D%DC%92%DC%9D&author=&title=&section=4&corpus-uri=&syriaca-uri=&text-id=

Please let me know if it does not match expected behavior.
