### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#28]
The left hand table of contents element is great, but we noticed something: When you view an individual work (http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=syriaccorpus.org/1) on a mobile device or if you shrink down a browser window (see attached photo), the TOC element stretches across the screen leaving a ton of white space and bumping the text down below.

Do we have any options for fixing this? Would it be possible to have a toggle on the display for the TOC? Or is there a better way to handle it?
![tableofcontents](https://cloud.githubusercontent.com/assets/11543800/22695850/3df7dee2-ed1a-11e6-936b-1bb8469192cd.jpg)

**Comment by jedwardwalters** [comment]
@wsalesky I just noticed this implementation, and I think it's great. I checked it on my phone/iPad, and it works perfectly.

**Comment by dlschwartz** [comment]
Agreed! That looks smart.

**Comment by wsalesky** [comment]
Great! I will close this then.
