### ISSUE TITLE
Number in titles

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#3]
This is happening on all of them, but for one example see: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=syriaccorpus.org/1

In the title, there is a number 1 between the English and Syriac titles. I think this might be the 1 that is supposed to be the header for the first paragraph. All other paragraphs have their section number right above, but not the first one.

**Comment by wsalesky** [comment]
I think the display could be improved, perhaps this is something we can discuss at out meeting @davidamichelson ?
