### ISSUE TITLE
Status element

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#30]
In the box on the upper right hand side (with Stable Identifiers, etc.), it would be great if we could have one more element below "Source" called "Status:"

Then we could clearly identify the editorial status of each work for our audience; i.e. "edited" "unedited" etc. (and we would come up with a standard nomenclature for what each status represents). 

Also, if you have any thoughts about the best way to include that in the TEI documents to make it easily extractable, let me know.

**Comment by wsalesky** [comment]
For Syriaca.org we use the 
`teiHeader/tei:revisionDesc/@status`

**Comment by jedwardwalters** [comment]
Okay, great. That's where I assumed it might go. Just wanted to double check up front.

**Comment by jedwardwalters** [comment]
Just editing this issue to remind myself that I need to create a "status" workflow and label descriptions.

**Comment by jedwardwalters** [comment]
This is done.
