### ISSUE TITLE
Corpus not displaying

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#31]
I just merged a set of edits that adds https:// to all the syriaccorpus.org URIs, and now the corpus isn't displaying. I assume that's my fault since the timing corresponds with my edit.

Do I need to fix something? Or is that a fix on your end? 

Here's the pull request (from syriac-corpus, not from syriac-corpus-app):
https://github.com/srophe/syriac-corpus/commit/ab5856d364e03205812f2bdc635229b055f8f2d3

**Comment by wsalesky** [comment]
I will take a look. I think it is related to the changed ids. Not sure why they are not being picked up.

**Comment by jedwardwalters** [comment]
Ah, the corpus does actually display. You just have to add https:// in the temporary URL for the dev site. So: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/1

**Comment by wsalesky** [comment]
Fixed. The config.xml, sets the URI pattern, which has changed. I updated it.

**Comment by jedwardwalters** [comment]
Thanks!
