### ISSUE TITLE
Update script

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#33]
In order not to slow down the browse we should not use the API but instead periodically synch the corpus title and author information (in Syriac and English) with NHSL.
A script will make sure that for each Corpus TEI file that has in it’s titleStmt title(s) and author(s) @refs with Syriaca.org URIS, the text nodes match the headwords in NHSL and SBD. Note this means that each corpus records should have both English and Syriac script titles and author information.

**Comment by wsalesky** [comment]
These works (referenced by the `tei:title/@ref`) do not seem to be up on either dev or production server. @nathangibson is this correct? I can not run this script, or even really test it successfully without these records.  Can you let me know when they are up. Thanks!

**Comment by nathangibson** [comment]
@wsalesky Sorry, I've been ill. I will try to get them up soon.

**Comment by wsalesky** [comment]
@nathangibson no problem, jut rounding up my issues list. Hope you feel better soon.

**Comment by nathangibson** [comment]
@wsalesky The work records are up now in NHSL. 

@jedwardwalters Can you take a look at the TEI in https://github.com/srophe/syriac-corpus-app/issues/33 (visualized at http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/8501 and contained works) and let me know if there's anything that needs correcting? Keep in mind that visualization is still going to get some tweaking and the volume title "Clavis of the Works of Aphrahat" is a placeholder.

**Comment by jedwardwalters** [comment]
@nathangibson This all looks good to me. I didn't check every single contained work, but they all seem to be displaying correctly.

**Comment by nathangibson** [comment]
@jedwardwalters Great. I just realized I missed @wsalesky 's point about needing to include Syriac titles for the script to work. I see that you have the Syriac titles in the corpus records. Would you want to paste them into the NHSL records, or should I do it? (With so few of them, I don't think it's worth scripting it.) 
E.g., for Demonstration 1 (work/8503), there would be two changes: 
1. in the teiHeader
```
<title level="a" xml:lang="en">Demonstration 1: On Faith</title>
``` 
would become 
```
<title level="a" xml:lang="en">Demonstration 1: On Faith — <foreign xml:lang="syr">ܬܚܘܝܬܐ ܕܗܝܡܢܘܬܐ</foreign></title>
```
2. In the body
```
<title xml:id="name8503-1"
                   xml:lang="en"
                   syriaca-tags="#syriaca-headword"
                   source="#bib8503-1">Demonstration 1: On Faith</title>
```
would become 
```
<title xml:id="name8503-1"
                   xml:lang="en"
                   syriaca-tags="#syriaca-headword"
                   source="#bib8503-1">Demonstration 1: On Faith</title>
<title xml:id="name8503-2"
               xml:lang="syr"
               syriaca-tags="#syriaca-headword"
               source="#bib8503-1">ܬܚܘܝܬܐ ܕܗܝܡܢܘܬܐ</title>
```

**Comment by jedwardwalters** [comment]
@nathangibson Sure, I don't mind doing that. And I think you're right. There are few enough titles that this could easily be done manually.

**Comment by nathangibson** [comment]
Thanks!

**Comment by jedwardwalters** [comment]
@nathangibson While I'm working on this anyway, would it make sense to go ahead and add the Syriac text of the title into the <titleStmt><title> element in the corpus files?

So, in other words, I would make the same change as your first one suggested above in both the /work and the /syriaccorpus files. Does that make sense?

**Comment by jedwardwalters** [comment]
Okay, @nathangibson--I changed all the files and just merged them into the dev server.

**Comment by nathangibson** [comment]
Awesome, thanks!

**Comment by jedwardwalters** [comment]
It looks like we can close this one? @wsalesky @nathangibson

**Comment by wsalesky** [comment]
I think so. @nathangibson ?

**Comment by nathangibson** [comment]
Yep
