### ISSUE TITLE
Displaying a poetic text

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#35]
@wsalesky ,
I have now uploaded a poetic text for display testing. Here's the code: https://github.com/srophe/syriac-corpus/blob/master/data/tei/26.xml

And here's the display: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/26

Two issues right now:
1) we will want poetic texts like this to be visualized line by line. So, in the TEI, I just labeled each line with a <l>...</l>. Perhaps we just need a slight adjustment in the formatting to make separate lines? Or maybe there's a better way to do this? I read the TEI guidelines, and this seemed like the standard way to represent poetic lines.

2) I think we'd also like the line number to display to the right of the text. So, whatever the value of n is inside the <l> element would display in the text. Is that possible in the current format? or would it be better to add numbers in the text with a separate tag?

**Comment by wsalesky** [comment]
How is this:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/26

**Comment by jedwardwalters** [comment]
This looks great upon an immediate inspection. 

I see that it pulled the number out, just like I asked--so that's great. Is that the best way to do that? I'm happy to do a different set up if there is a better/easier option for how that gets represented.

Also, a very small issue that might be related to how best to represent the number in the TEI: it seems to be displaying the line number in the Syriac font instead of our default english font.

**Comment by wsalesky** [comment]
This TEI format work fine. Let me see what I can do about the Syriac font on the number, that was not intentional.

**Comment by wsalesky** [comment]
Fixed font.

**Comment by jedwardwalters** [comment]
Perfect. Thanks. I'll let you know if I have any other thoughts on this later when I have a few more minutes to look, but if not I'll just close the issue.

**Comment by wsalesky** [comment]
Sounds good.

**Comment by jedwardwalters** [comment]
Okay, two quick thoughts here:
1) The Syriac font seems rather large, particularly in comparison with the other texts. Is there a particular reason why it's that large?

2) I wonder if there's an easy way that we could make a toggle display switch so that if someone wanted to view it not broken out line by line, they could easily do so?

Note: on point number 2, I'm thinking of future texts too where I think it might be useful to have toggle display options. For example, when we include biblical texts, it might be nice to have the ability to show verse-by-verse layout or chapter-by-chapter without verse numbers, etc...

If that's too complicated, no worries. Just wondering what's possible and how much work it involves.

**Comment by wsalesky** [comment]
Yes, we can have toggle displays, I will just need to add some better css classes so it is easier to switch. And we can adjust the font size for Syriac, I'm not sure why the default is so much larger on the Corpus then on Syriaca.org.

**Comment by jedwardwalters** [comment]
Great! Thanks.

Figuring out what kind of display toggles we need will probably be sort of ad hoc for a little while as the corpus grows--and we are in most cases reliant upon the kind of information that people chose to include in their transcriptions (i.e. like whether they included page breaks, etc).

For example, right now I'm working on another poetic text as a test case, and it does include page breaks from the source book. So on that one, it might be nice to have a "page" view that keeps all the text in paragraph form and notes where the breaks happen and then have the line-by-line view option (with or without page breaks). I'm trying to imagine all the ways people might want to visualize the corpus, so I'm just trying to get a sense of what's possible (without creating too much extra work for you!)

**Comment by wsalesky** [comment]
Most of that sort of stuff is handled by JavaScript and CSS, so, not to complicated.

**Comment by jedwardwalters** [comment]
Closing this issue to consolidate text structure/display issues.
