### ISSUE TITLE
Syriac search

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#36]
Is there any way to adjust our search so that a search for a word without vowels will catch the same word if it happens to include vowels?

For example, if I search ܡܐܡܪܐ, I get these results:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=ܡܐܡܪܐ

But in the new Jacob text, which includes vowels, I have to search for ܡܺܐܡܪܳܐ to get the same word to show up:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=ܡܺܐܡܪܳܐ

If we can't cross search with/without vowels, that could significantly decrease the value of our search function. I don't know if this is possible, so we need to work this out at this early stage so that we can figure out how to work around it if needed.

**Comment by davidamichelson** [comment]
Yes, we should be able to supply Winona with the list of the vowels and
perhaps have a box to check for if the search should include vowels or not.

**Comment by dlschwartz** [comment]
@davidamichelson, @jedwardwalters How would this suggestion work in practice Dave? Would searching "with vowels" accommodate East and West or would we need separate searches for those? What about dots? Would we exclude all/most of them from every search?

**Comment by dlschwartz** [comment]
Seyame is a particular problem since it can appear just about anywhere in a word.

**Comment by dlschwartz** [comment]
Would anyone want to search only the vocalized texts? Maybe but how often?

How about this? 
1. take a string input into a search box, strip out the vowels and dots other than seyame
2. search the corpus for words while ignoring the vowels/dots in the corpus words, except for seyame
3. when a search string includes a seyame, return results from the corpus for relevant words containing a seyame no matter where the seyame appears in that word

**Comment by davidamichelson** [comment]
These can be included on an excluded characters list. Please put this on the agenda for Wednesday.

**Comment by dlschwartz** [comment]
Maybe we want to accommodate some users who just want to search for dots. The ability to do so might even help in proofreading the corpus.

I'll put this on the agenda for discussion tomorrow.

**Comment by jedwardwalters** [comment]
I’m trying to imagine a scenario where someone would need/want the vowels as part of the search. I suppose if our corpus got large enough this could be useful, but as a bare minimum we need the ability to search for lexemes without any pointing (including seyame, as Dan mentioned) that will still include results from pointed and unpointed texts.

**Comment by dlschwartz** [comment]
What about students who can't yet read unvocalized text looking for a word? 

Do we markup language and vocalization in the header? It might be nice if a user in the process of learning the language could at least browse for East Syriac vocalized text or West Syriac unvocalized.

**Comment by jedwardwalters** [comment]
@davidamichelson and @dlschwartz, did you guys discuss this with Winona today?

**Comment by dlschwartz** [comment]
We did, and Winona is working on it. It's great to have eastern and western vowels in the corpus. That should help. Thanks.

**Comment by wsalesky** [comment]
@jedwardwalters I am going to start working on this search issue next> Can you give me three different examples with the search term, with and without vowels, and expected search results. 
Thanks!
-Winona

**Comment by wsalesky** [comment]
@jedwardwalters @davidamichelson @dlschwartz 
I am investigating this issue currently. I will probably need some help testing solutions and gathering data. 

**First step is to clarify what we need.** 
My understanding is that we essentially need to be able to search the text with or without diacritics and with or without vowels, are there other possible confounding issues? 

**Information that could help with testing**
Is there a unicode range(s) that represents the vowels and/or diacritics that will need to be 'ignored'? 

Thanks all.

**Comment by jedwardwalters** [comment]
So sorry, @wsalesky, I meant to answer your previous request over the weekend and it totally slipped my mind. I'll try to give you some examples later today, and I'll also try to answer your other questions.

**Comment by jedwardwalters** [comment]
Unicode chart for Syriac:
http://www.unicode.org/charts/PDF/U0700.pdf

It looks like most of the vowels are in the 073 and 074 columns.
The 070 column appears to be all punctuation, and we may want to exclude those too in case any of those symbols happen to appear between words in a string.

**Comment by jedwardwalters** [comment]
Examples for searching:
Example 1:
Let's say I cut and pasted a word from a text with Eastern vowels and wanted to search for occurrences, like: ܢܲܦܫܵܐ

I would expect it to return that word in that same form, but also with no vowels (ܢܦܫܐ) and any that happen to have "western" vowels (ܢܰܦܫܳܐ).

Example 2:
If I searched for a no-vowel word: ܦܘܪܫܢܐ

I'd want it to hit both:
ܦܘܽܪܫܳܢܳܐ
ܦܘܼܪܫܵܢܵܐ

Example 3:
Searching for a word that is fully vocalized with both vowels and dots that signify pronunciation issues (i.e. the dot below this word is not a vowel, it's another kind of character--I think all of these are represented in that unicode range too)
ܡܰܠܰܐܟ݂ܳܐ

Should return:
ܡܠܐܟܐ
and
ܡܲܠܲܐܟ݂ܵܐ

Let me know if you need more!

**Comment by wsalesky** [comment]
@jedwardwalters Thanks, this is a good start. Let me run some experiments and get back to you.

**Comment by davidamichelson** [comment]
@jedwardwalters can you write a Unicode equivalency table for Winona of the following:
Table 1: Which vowel characters should be treated as identical for the sake of search
Table 2: Complete list of characters to be searched for (the 22 consonants?) (ie not ignored as vowels or punctuation) in a non-vocalized simple search

**Comment by jedwardwalters** [comment]
@davidamichelson I just made this. Is this what you had in mind?
[Syriac Character Unicode Tables.pdf](https://github.com/srophe/syriac-corpus-app/files/1356733/Syriac.Character.Unicode.Tables.pdf)

**Comment by wsalesky** [comment]
@jedwardwalters Finally moving forward on this. I think I have a solution, but need to do some additional testing. For these examples: 

> Examples for searching:
> Example 1:
> Let's say I cut and pasted a word from a text with Eastern vowels and wanted to search for occurrences, like: ܢܲܦܫܵܐ
> 
> I would expect it to return that word in that same form, but also with no vowels (ܢܦܫܐ) and any that happen to have "western" vowels (ܢܰܦܫܳܐ).
> 
> Example 2:
> If I searched for a no-vowel word: ܦܘܪܫܢܐ
> 
> I'd want it to hit both:
> ܦܘܽܪܫܳܢܳܐ
> ܦܘܼܪܫܵܢܵܐ
> 
> Example 3:
> Searching for a word that is fully vocalized with both vowels and dots that signify pronunciation issues (i.e. the dot below this word is not a vowel, it's another kind of character--I think all of these are represented in that unicode range too)
> ܡܰܠܰܐܟ݂ܳܐ
> 
> Should return:
> ܡܠܐܟܐ
> and
> ܡܲܠܲܐܟ݂ܵܐ
> 
> Let me know if you need more!

Can you give me a list of expected results (and what is NOT showing up on the dev site)? I'm testing on my local machine, of the new updates work, we will have to update the version of eXist on the dev server.

**Comment by jedwardwalters** [comment]
Hi Winona,

I was just about to test this, but it looks like the dev site is down?

Jamey

**Comment by wsalesky** [comment]
It is back up.

**Comment by jedwardwalters** [comment]
Okay, it's possible that I'm misinterpreting your question, so please let me know if I'm misunderstanding what you're asking. 

When I search example 1 (ܢܲܦܫܵܐ), I only get returns that exactly match it (with those same points). So, I'm not getting ܢܰܦܫܳܐ or ܢܦܫܐ. Likewise, if I search either of these latter spellings, I only get search results that match those forms exactly.

So, ideally, if I search for any of these spellings, it would produce all of the following results together:

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%A2%DC%B2%DC%A6%DC%AB%DC%B5%DC%90&start=1&perpage=59

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%A2%DC%B0%DC%A6%DC%AB%DC%B3%DC%90

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%A2%DC%A6%DC%AB%DC%90&start=1&perpage=26

Does that help?

**Comment by wsalesky** [comment]
Right, the new version of eXist (currently only running on my machine, but coming soon to dev) should be able to resolve this issue, but I am attempting to do some testing while being mostly Syriac illiterate. On my local version I get 106 hits when searching for 'ܢܲܦܫܵܐ' which seems to combine all the results of the the three searches above.  (See screen shot.)

I think this does solve the major search issues, so I will work on getting the new version installed on dev and you can do some additional testing. 

<img width="1077" alt="screen shot 2017-12-04 at 10 06 53 am" src="https://user-images.githubusercontent.com/1168206/33559493-f4730988-d8da-11e7-955b-16d9a8d41371.png">

**Comment by jedwardwalters** [comment]
Yes! Your screen shot looks perfect. 

Question: is there a way for this to toggle? I think the default should be that it returns all results, but if someone wants to search something with only a certain vowel pattern, is that possible as an option?

As an example of how this would be useful, some verb forms have the same consonants as a noun, but different vowel inflections. So if someone wanted to search for only ܟܬܳܒܐܳ (book), the removal of the vowels would presumably also return results for ܟܬܰܒܐܶ (writing). 

If the toggle isn't an easy thing to do, the high priority item is the search results returning all results. Thank you!

**Comment by jedwardwalters** [comment]
Or maybe even better than a toggle option is simply a different search box on the Advanced Search page. So the search bar at the top of the page always defaults to all results. Then, on the Advanced Search, maybe a dedicated search item could return only results that match exactly?

**Comment by wsalesky** [comment]
@jedwardwalters This is finally available for testing on the dev server: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/search.html?q=%DC%A2%DC%B2%DC%A6%DC%AB%DC%B5%DC%90

Please take a look and let me know if it is behaving as expected. Thanks!

**Comment by jedwardwalters** [comment]
Okay, thanks! I did a couple of quick searches, and they seemed to work as expected. I'll try to do more soon.

**Comment by jedwardwalters** [comment]
@wsalesky This issue seems to have backtracked. Last time I tested this, I was getting the expected results, but now it's only returning exact matches re: presence of diacritics.

**Comment by wsalesky** [comment]
@jedwardwalters Yes, sorry we had to roll back the version of eXist on the dev server due to an unrelated issue. eXist has just release v 4.0 which I will be testing this weekend. My hope is we can move to the latest version next week.

**Comment by jedwardwalters** [comment]
Oh good, I'm glad there's an easy explanation for this! I'll leave this issue open to remind myself to come back and test, but we should be able to close it soon.

**Comment by wsalesky** [comment]
@jedwardwalters I think this can be closed now.
