### ISSUE TITLE
Corpus URIs for Work containing other Works

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#38]
Should I be minting syriaccorpus URIs for collected works that contain individual works? For example: The Demonstrations. I know we need syriaca.org/work URIs for such collected work titles, but I actually can't think of a reason why we would need corpus URIs for them.

Any thoughts, @nathangibson @davidamichelson @dlschwartz?

**Comment by davidamichelson** [comment]
That seems right, corpus IDs should always correspond to a specific file. One URI per file. If no file, no corpus URI.

**Comment by nathangibson** [comment]
I would agree with that approach too.

**Comment by jedwardwalters** [comment]
Okay, that's what I thought. Just wanted to make sure I wasn't missing something!
