### ISSUE TITLE
New texts not displaying

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#39]
I keep having this issue where new texts that I add aren't automatically showing up on the dev site. Most recently, it's texts 28 and 29 in the corpus. Any ideas? Perhaps something I'm doing wrong?

**Comment by wsalesky** [comment]
Sorry for the delay, I added them manually. It is unclear what is making some of these fail via webhooks and not others. I am going to leave this open so we can investigate it more.

**Comment by wsalesky** [comment]
I found the problem in the git-sync script. Let me know if you have any additional problems. (I pushed the most recent commit, 30.xml, 31.xml and 32.xml)

**Comment by jedwardwalters** [comment]
Great, thanks!

**Comment by jedwardwalters** [comment]
FYI, I just added three new texts and they went up immediately. Thanks!
