### ISSUE TITLE
Display fonts

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#4]
Some of the pages (for me anyway) are displaying in a standard unicode font, such as:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=syriaccorpus.org/1

But others are displaying in a custom font (like Estrangelo Edessa):
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=syriaccorpus.org/10

Do we have the ability to let people customize which font they appear in? Or should we just have a standard font?

**Comment by wsalesky** [comment]
Custom fonts are supposed to be used if there is a xml:lang element, however I suspect there are some elements that we simply have not used in Syriaca.org that are not yet specified in the XSLT. 

I will take a look at the XSLT. I suspect there will be a bit of customization needed to make things look right.

**Comment by davidamichelson** [comment]
Ideally, and this would be a nice feature to have for all instances of the
Srophe app, we would like to have an option where users could force it to
display with a choice of font.

**Comment by wsalesky** [comment]
This most likely can be easily achieved via JavaScript. Let's make sure it all displays correctly in the specified font, and then work on a 'toggle font' feature.

**Comment by wsalesky** [comment]
Not all tei:p elements have xml:lang attributes, so it is not accessing our css defined styles.

**Comment by jedwardwalters** [comment]
Ah, okay. I can take care of that!

**Comment by jedwardwalters** [comment]
Done.
