### ISSUE TITLE
Text structure and visualization

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#41]
@wsalesky After a couple of weeks of thinking about this, we worked out a system for the text structure for the corpus. Hears what we came up with:

Certain elements are allowed to contain Syriac text, but these text blocks must correspond to the intellectual structure of the text. The allowed elements are: tei:div, tei:ab, tei:p, tei:lg, tei:l (only poetry). The numbering for these elements MUST occur as @n with the token label as should be displayed (thus “1” or “Preface” or “2a”; these need not be unique). When numbers occur in the source edition/text or if there is need for additional mark up the token labels may also occur in the text node of a tei:head. These tei:head text nodes will always display with the text, and the tei:head will continue to be a link for the TOC box.

For texts without any real divisions, the entire text will be in a single tei:div/tei:ab element.

For numbering systems that break the intellectual structure of the text, only tei:milestone (with @type if applicable, also include @ed with syriaca.org/bibl URI to show source, eventually we will use @edRef to contain CTS citation heres as well), tei:pb, tei:cb, tei:lb elements without text nodes should be used. (For these break elements, @ed must included with the syriaca.org/bibl URI as a value, if multiple page numbering from same edition, then include @type or @subtype to distinguish, eventually we will use @edRef to contain CTS citation heres as well.) The numbering for these elements must occur as @n with the token label as should be displayed (thus “1” or “Preface” or “2a”; these not need be unique). These will only optionally be displayed in the HTML.

For now, see the following three examples for visualization purposes:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/1.xml 
https://github.com/srophe/syriac-corpus/blob/master/data/tei/100.xml
https://github.com/srophe/syriac-corpus/blob/master/data/tei/27.xml

**Comment by jedwardwalters** [comment]
@davidamichelson When a text comes from a manuscript, not a printed edition, what should we do for the "ed" source in the pb elements? We decided to use bibl URIs for printed editions. 

Ideally, I suppose we would have a manuscript URI to use instead of a bibl URI, but then of course we'd have to create a manuscript catalogue file for every manuscript we use. Thoughts?

**Comment by davidamichelson** [comment]
This is related to https://github.com/srophe/syriac-corpus/issues/48

**Comment by davidamichelson** [comment]
Related https://github.com/srophe/syriac-corpus-app/issues/42

**Comment by davidamichelson** [comment]
Default display for TOC should be tei:div

**Comment by jedwardwalters** [comment]
Okay, sounds good. Should I just use the next available URI from the Wright Decoder google doc? Or choose a block of numbers for this purpose?

**Comment by wsalesky** [comment]
Will the `tei:div, tei:ab, tei:p, tei:lg, tei:l ` all have a type attribute? Or will that only be for `tei:div` and `tei:ab`?

**Comment by jedwardwalters** [comment]
Hmm. Good question. Right now I can’t think of a reason we would need to have a type on tei:p or tei:l. It’s possible that in some kinds of poetry we might want to use a type on tei:lg, but I’m not positive about that.

**Comment by dlschwartz** [comment]
tei:div and tei:ab -- definitely

tei:p cannot take a type attribute (there's actually an ongoing conversation at this very moment on the TEI list). I believe the same is true for tei:l. 

I could imagine typing different kinds of stanzas (and tei:lg allows a type attribute) but I'm not sure why we would need to do so. If we wanted to make users aware of different kinds of poetry in the collection, it seems like the header would be a better place to do that. This could be useful if an author changed stanza types in a single work. I think we should only add this later if we need to do so.

**Comment by davidamichelson** [comment]
I think you should use the bloc that you started for the French and HMML
uris?

**Comment by jedwardwalters** [comment]
Okay, will do. I thought of that and meant to mention it. That’s an easy solution.

**Comment by wsalesky** [comment]
@dlschwartz  Thanks, I'm just writing the code to generate the toggle function, some elements will toggle on the @type and some will have to toggle based on the element I think. Should have something to look at on Wednesday.

**Comment by wsalesky** [comment]
Still a work in progress.

**Comment by wsalesky** [comment]
Will need additional testing, but working fairly well.

**Comment by wsalesky** [comment]
@dlschwartz  @jedwardwalters  I think this has been resolved. If not please reopen.
