### ISSUE TITLE
Milestone types

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#43]
List of controlled values for tei:milestone/@type:

**Comment by dlschwartz** [comment]
@jedwardwalters We discussed in our meeting today that each of the milestone-like elements should have a type attribute. This would include the elements ab, pb, milestone, etc. I'm guessing you have this in mind already but I wanted to confirm. Thanks Jamey!

**Comment by jedwardwalters** [comment]
@dlschwartz Yes, I think that's the case so far. At any rate, I'll make sure it is moving forward.

**Comment by wsalesky** [comment]
Closer now. Will need to test some additional types.

**Comment by wsalesky** [comment]
@jedwardwalters can this be closed? If not is there an action item that needs to happen here?

**Comment by jedwardwalters** [comment]
Yes, I think it can be closed.
