### ISSUE TITLE
 Corrections additions button is not yet functioning

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#51]

**Comment by wsalesky** [comment]
This is fixed, although the email is not set up to go to the correct editors.

**Comment by davidamichelson** [comment]
Also the recaptcha did not work on the Gazetteer, is this the same fix?

**Comment by wsalesky** [comment]
Production or development?

**Comment by davidamichelson** [comment]
Not sure, was reported by a user yesterday
