### ISSUE TITLE
PDF Export 

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#53]
This is not a high priority item...and if it's too complicated, it's not a big deal if we don't have it.

I was wondering if it might be possible to have a feature where someone could easily export a PDF of just the Syriac text of whatever corpus item they are viewing. I know someone could make a PDF of the web page, which would include the text, but it would also include everything else on the page as well. So, I thought it might be useful if we could easily make a PDF of just the text.

I know Oxygen has issues with Syriac characters when you try to produce a PDF, so I don't know how that will affect this.

I'm thinking that this would be a handy feature for anyone who is helping us proofread the texts, as it would be much easier to mark up typos and such from a printout.

**Comment by dlschwartz** [comment]
@jedwardwalters I'll put this on the agenda for next week. Thanks.

**Comment by wsalesky** [comment]
I think there is an issue with the Syriac fonts.

**Comment by davidamichelson** [comment]
There should be a fairly easy solution to this.

@wsalesky, we would like to make a simplified PDF output of the TEI:body plus the citation.

@jedwardwalters  will make a one page sample PDF by hand so you can see what this might look like.

I think that we will want to use the PDF engine and TTF version of the meltho fonts that James Bennett worked out if I remember.

**Comment by wsalesky** [comment]
@davidamichelson 
That seems correct, did we ever get the TTF version of the fonts. I think we were still waiting on them? Or were we waiting for permission to use them?

**Comment by davidamichelson** [comment]
Not sure, but please contact Jim directly and ask.

**Comment by wsalesky** [comment]
Updated print css, excludes links on words, and both right and left columns. Let me know what else we might want to change for the print copy.
