### ISSUE TITLE
Sedra allowed characters

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#54]
Get a list of allowed characters for Sedra, some words are breaking the API:
 ܕܝܪ̈ܐ/ܘܕܝܪܐ/

 ܠܥܢܗ܂

The backslashes are sent, no word is found (obviously). The second example sends a period, which also returns no results.

**Comment by jedwardwalters** [comment]
That first one just needs to get fixed on my end (I imagine). The backslashes shouldn't be there, and they probably represent a textual variant or something. 

Do you remember off hand where that came from?

**Comment by wsalesky** [comment]
It is in this one: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/10

Section 2.

**Comment by jedwardwalters** [comment]
Thanks! And yes, that's just a problem with the text. I'm sure there are other places where this happens (depending on the idiosyncratic practices of the transcribers), and they'll have to get smoothed out slowly with proofreading.

**Comment by wsalesky** [comment]
Okay. I still need to handle periods I think. So you can leave the issue open.
