### ISSUE TITLE
Need to specify English text in English additions to display

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriac-corpus-app#57]
See display issues here (there is a xml:lang='syr' on the tei:body):
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/1

**Comment by jedwardwalters** [comment]
@wsalesky the lang tag doesn't have to go on the tei:body if that's easier on your end.

**Comment by wsalesky** [comment]
I think it is fine. I just need to adjust the XSLT to be specific when it is not Syriac.

**Comment by jedwardwalters** [comment]
Thanks. I was going to ask you about that display issue. But you're on it already.

**Comment by jedwardwalters** [comment]
Maybe you saw this on the same page, but I think this also affects the section numbers (wrapped in <head>), which are right justified and the wrong font. 

Also, related: the section numbers are no longer showing up in the table of contents box. Perhaps because we added a type to them?

**Comment by wsalesky** [comment]
Hum, actually it is probably better to only have the xml:lang='syr' on the most immediate (to the Syriac text) parent element. Because those numbers are inheriting the xml:lang attribute from the tei:body.

**Comment by jedwardwalters** [comment]
Okay. Got it. I can make that change.

**Comment by jedwardwalters** [comment]
Done.
