### ISSUE TITLE
Multiple word search in a string

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#59]
We need a way to search for two words within a certain range (if the range can be variable, that would be great--if not, we can just set it at 10 words as a default).

I'll provide some examples from this text:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/1

Example 1:
If I searched ܗܝܡܢܘܬܐ ܡܬܪܟܒܐ, I would expect it to return the first line of section two:
ܗܝܡܢܘܬܐ ܓܝܪ ܒܨܒ̈ܘܬܐ ܗܘ ܣܓܝܐ̈ܬܐ ܡܬܪܟܒܐ܂
(The search string words are the first and final words of this sentence.)

Example 2:
If I searched ܕܘܝܕ ܡܫܝܚܐ, I would expect it to return the following line in section seven:
ܕܘܝܕ ܩܕܡ ܐܟܪܙܗ ܥܠ ܡܫܝܚܐ

Let me know if you need more examples!

**Comment by wsalesky** [comment]
@jedwardwalters I have changed the KWIC (keyword in context) display to be a more 'Google' like display, this enables the display of phrases, and fuzzy search results, and eliminates the duplicate lines. Downside is that it eliminates the line numbers, however the matches are still linked (although I noticed the anchors are not working, I will file a bug). 

Please take a look and let me know what you think of the new display and how/if you want any tweaks.

**Comment by wsalesky** [comment]
Also, did we mention at one point highlighting the search results on the page? (when you click through from a search?)

**Comment by jedwardwalters** [comment]
@wsalesky 
When I do a proximity search, do I need to type an extra character? Or just put two words in the search bar? I've tried it both ways. I'm just trying to make sense of the results I'm getting.

And yes, at one point we mentioned highlighting the search results on the page when you click through. I think that would be helpful.

**Comment by wsalesky** [comment]
I think I have the fuzzy search enabled, is the search meeting your expectations, or do I need to adjust it?

**Comment by jedwardwalters** [comment]
Okay, here's an example search. Sorry, this is kind of long:

First, I searched two words without using the quotation marks or the + sign. So, I just typed in the two words with a space (ܕܗܫܐ ܫܡܥ). And I set the proximity to 5. Here's the results I got (note: there were more, but these top two illustrate my question):
![advanced search](https://user-images.githubusercontent.com/11543800/30409490-61beb002-98d3-11e7-9c5c-1eec602e98ce.jpg)
So, in the first one, it pulls up the right text (the one I picked as an example), but it also includes a use of just one of the words without the second word. So, there are two highlighted uses of ܫܡܥ in Demonstration 1, but only one of those is in proximity to ܕܗܫܐ. Moreover, in that image, there's a strange duplication of two words. The full phrase should be ܕܗܫܐ ܕܝܢ ܫܡܥ, but in the search results it shows up as ܕܗܫܐ ܕܝܢ ܕܝܢ ܫܡܥ ܫܡܥ.
The two occurrences of ܫܡܥ are in different paragraphs, as seen here (the one I wanted is the second highlighted one):
![advanced search 2](https://user-images.githubusercontent.com/11543800/30409614-491882f2-98d4-11e7-920f-f9f37c6d918d.jpg)

Okay, so that's search result #1 from Demonstration 1. Now onto the second one: It seems like none of the results in result 2 are actually the two words in the specified proximity. They are just one off occurrences of each word.

So, am I doing the search wrong?

Then, if I do use quotation marks and the + sign, I get this result:
![advanced search 3](https://user-images.githubusercontent.com/11543800/30409787-3c2fd8e6-98d5-11e7-91da-4612273a7e24.jpg)

It shows the correct Demonstration (and this is the only result it gives), but it doesn't show any text.

**Comment by wsalesky** [comment]
@jedwardwalters Thanks for the examples. I think I need to do some more work on phrase searching. I will let you know when I have it working.

**Comment by wsalesky** [comment]
There is a bug in KWIC processing for phrase searching in eXistdb. 
See: https://github.com/eXist-db/exist/issues/833

**Comment by jedwardwalters** [comment]
@wsalesky I want to follow-up on this issue. I think that the proximity search works, but perhaps the results could be cleaned up somehow? 

For example, when I search for a set of words (ܚܒܝܒܝ+ܚܕܝܬܢܝ) with a proximity of 10, I get the following results:
![search1](https://user-images.githubusercontent.com/11543800/36211707-02221f38-1170-11e8-9abf-d4e343c17055.jpeg)
The first two lines of these results are good/correct. But the following lines only appear to find one of the words. So, it seems to me that only the first two lines should display.

I see the previous comment above about a bug...is that still the issue?

**Comment by wsalesky** [comment]
@jedwardwalters  This is a bug in eXist-db. I may be able to hack around it. How would you like to do proximity searching? Do you want to use the dropdown on the search, if so do you want it for every field or just keyword, do you want a default distance set behind the scene so the users do not have to worry about it?

Let me know and then I will see what I can do about the display.

**Comment by jedwardwalters** [comment]
I think proximity searching should only be in the advanced search option, and I think it only needs to be on keyword.

I think being able to customize the default distance is a nice feature, but if it would simplify things I think we could do a default of 10 words or so.

**Comment by wsalesky** [comment]
If it is only on the keyword then I think I can make the variable proximity work. Let me give it a try.

**Comment by jedwardwalters** [comment]
I can't think of a reason why it would need to be anywhere else.

**Comment by jedwardwalters** [comment]
Apparently we had an old issue open on proximity searches. Closing here too.
