### ISSUE TITLE
Toggle Font Display

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#6]
Split from #4 

Winona please research (and perhaps consult with James Bennet if SEDRA has this), a display toggle that would allow users to choose from three possible Syriac fonts that would force the display of all Syriac on the page (or in the user experience?) in the same font.

The options would be

Default (i.e. display the file as encoded)
Estrangela (use Estrangelo Edessa Font)
East Syriac (what font do we current use here)
West Syriac  (what font do we current use here)

This feature should implement on the Syriaca.org version of the app as well.

**Comment by wsalesky** [comment]
I have added this function. I will need to work out a more attractive layout for the 'swap' menu.

**Comment by wsalesky** [comment]
Note: this will only work with elements that have the xml:lang attribute.
