### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#60]
@wsalesky, here are a few things I've been thinking about in terms of brainstorming the next step of production for the Corpus (i.e. aside from just adding more texts, which I'm working on...slowly):

Content
1) Content for the index/home page
2) Creation of a "how to contribute" page
3) Somewhere to explain the various 'status' levels for the documents

Tools/usability
1) Searching for multiple words in a string (I know you're working on this already)
2) Search function that can account for lack or presence of vowels (https://github.com/srophe/syriac-corpus-app/issues/36)

**Comment by jedwardwalters** [comment]
@wsalesky I just saw the index page, and it looks amazing!

**Comment by wsalesky** [comment]
@jedwardwalters great (re: index page)! I will keep you up to date on the search issues as they develop.

**Comment by jedwardwalters** [comment]
Closing this one to consolidate what has been done and what still needs to get done.
