### ISSUE TITLE
Minting Work Records for BHSE

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#64]
@nathangibson @dlschwartz @davidamichelson 

NOTE: This is not specifically a corpus issue--I just couldn't think of a better place to create the issue.

I thought of this issue this morning, but there was never a good time to squeeze in a question about such a small matter. I figured creating an issue would work better.

A few weeks ago I tried to reserve a URI for a work number in BHSE using the form. It's for an apocryphal text I'm translating for a volume. So, I was trying to reserve the URI just so I could assign the text a stable reference number, since this text is not found in any other clavis.

However, it's not clear to me that the reservation actually worked. The number I was trying to reserve is 10523, but I was never prompted to fill out further information or given a chance to download the file. 

So, I guess what I'm asking is: is there any way to know for sure if it worked? I didn't want to try again and then end up creating multiple records that would then be in conflict. So, can anyone confirm whether the number 10523 has actually been reserved?

**Comment by wsalesky** [comment]
@jedwardwalters Technically I think this belongs here: 
https://github.com/srophe/srophe-admin

I see that 105253 already exists: http://wwwb.library.vanderbilt.edu/work/10523

I will take a look at the forms and see what is going on.

**Comment by nathangibson** [comment]
@jedwardwalters Work URIs should still be reserved in this spreadsheet https://docs.google.com/spreadsheets/d/1-vDeuCL7cVZSz6Xfl5KsMsv9qQ5WYPIFfBaExNeTTkA/edit?usp=sharing until we all agree that the admin form is working well enough to move to that system. Feel free to just add stuff to that spreadsheet using the "Next avail. ID". 
The admin module should have seen 10523, but there are other work URIs reserved in this spreadsheet that the admin module doesn't know about.
@wsalesky Let me know if you're ready for me to test reserving some ranges.

**Comment by jedwardwalters** [comment]
Thanks, @nathangibson. I'll be sure to use that in the future!

**Comment by jedwardwalters** [comment]
Closing this issue.
