### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#65]
@wsalesky Following up on the problems Dan was having, I also did a pull request/commit last night when the dev server was down, and those materials are not showing up when I try to view them in HTML.

Here's the link to the commit:
https://github.com/srophe/syriac-corpus/commit/a585867bf35643542f8720ce9cc670a4741b6097

(Pull request #115 in the syriac-corpus repository)

**Comment by wsalesky** [comment]
@jedwardwalters The dev server is down again this morning. When it is back up I will push that commit. Thanks for letting me know.

**Comment by wsalesky** [comment]
They should be up now. Let me know if I missed anything.
