### ISSUE TITLE
Poetic text test

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#68]
@wsalesky I added a poetic text tonight for testing with the display:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/259

Let me know what you think of the structure I used here and if you have any suggestions or corrections (@dlschwartz and @davidamichelson feel free to weigh in on this too).

**Comment by jedwardwalters** [comment]
@wsalesky On the example posted above, I'm wondering about all of the buttons at the top for toggling the display (body, ab, line, etc.). Most of them don't do anything. The only one that really matters here is line group. So, I have two questions:
1) Is there a way that we can determine which buttons show up?
2) Can they be named by type? For instance, I'd prefer that "line group" show up as "stanza"

Thoughts?

**Comment by wsalesky** [comment]
@jedwardwalters I noticed that also. I think it is time to revisit that function. Is there any indication in the TEI that this is a poem? Or do we always want "line group" to translate as "stanza" I will also debug the functionality of this, as it doesn't work quite as expected.

**Comment by jedwardwalters** [comment]
I don't think there's any indication that it's a poem. Perhaps we could make one? Would it make sense to put a @type attribute on the body element? It could just be either prose or poetry for our purposes. I have used line group somewhere else...maybe just for the opening rubrics of Narsai's works.

**Comment by jedwardwalters** [comment]
And I'm also totally open to revisiting that function. If it's overly clunky or not doing what we want, we can definitely change tactics.

**Comment by wsalesky** [comment]
@jedwardwalters let me take a look at the function and see what I can do with the data as is. I will let you know. (Maybe by tomorrow.)

**Comment by wsalesky** [comment]
@jedwardwalters I edited this function. We may want to have certain features show as default. For example on the poem, perhaps we want the display to show lines as the default? This simply turns on or off css, so it is not hard to change. Let me know how you want this 'show' feature to function.

**Comment by jedwardwalters** [comment]
I like the way it looks now. Let me play around with it a bit and see what issues arise. For example, I'm not sure we need the "title" on any of the texts. I'll get back to you on this.

**Comment by jedwardwalters** [comment]
Okay, @wsalesky, here are some thoughts on this feature (Sorry in advance that this is long!):

1) Title - I don't think we need the number to pop up on any of the titles. So, I have a question: would it be an easy CSS thing to have the text of whatever is marked as a title display in red when this is toggled? If not, can we just remove the title feature as an option to toggle?

So, in this example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/1
If we toggled the title button, I would want that first line (ܬܚܘܝܬܐ ܗܝܡܢܘܬܐ) to turn red instead of the number popping up next to it.

2) I think the "section" toggle works well (on the same example given above), and I think it should be toggled on by default.

3) This example doesn't have a "title" option: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/26
Maybe something's wrong in my markup.

4) For this one (and all poetic ones), I do think the "line" feature should be toggled on: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/27

5) In that same example just given, though, I don't know why this one shows up as "ab" instead of "title"  -- Thoughts?

6) I have two things on this example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/100     

- I'd like for the toggle button to say "verse" instead of "ab" - so maybe there's a way of specifying the "type" associated with the ab element? Also, on this example, the ab/verse toggle isn't showing up at all: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/119

- The "chapter" toggle is a bit odd here. Mostly it's the English title display that is odd. It's showing up at the end of the first line of syriac. It would be great if the English title were offset on its own line (that may be a fix in the TEI--if so, let me know)

7) The titles show up on this example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/186 and this one: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/187 differently than other texts (gray text at the top, left justified). I like this display, actually, I'm just pointing out that it is different. Also, these texts don't have any title toggle feature. Don't know if that's related.

8) This example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/188   doesn't have anything in the toggle view box

**Comment by wsalesky** [comment]
@jedwardwalters this is a combination of encoding differences and needs for xquery tweaks. 

Encoding differences account for:
5. Is caused by ` <div type="ab" n="0">` instead of ` <div type="title" n="0">`
6. a. You could add a type = 'verse' to the tei:ab element. I will amend the xquery to look for that.
    b. This might be solved by adding the xml:lang='en' to the chapter tag, if not I will have to edit  some code.
7. This title is encoded as : 
`<head> <title>Book of the Laws of the Countries - <foreign xml:lang="syr">ܟܬܒܐ ܕܢܡ̈ܘܣܐ ܕܐܬܪ̈ܘܬܐ</foreign></title></head>`
Most titles are encoded as: 
`<div type="title" n="0"><ab xml:lang="syr">ܐܘܢܓܠܝܘܢ ܕܡܬܝ</ab></div>`

I think the rest require xquery tweaks. I will work through them this weekend.

**Comment by jedwardwalters** [comment]
Thanks. I'll make these changes.

**Comment by jedwardwalters** [comment]
@wsalesky Okay, I took care of some of the things mentioned above. I'll go back through soon and post some other issues individually as needed. I'll leave this open for now if you are still working on it.

**Comment by wsalesky** [comment]
I will take a look tonight.

**Comment by wsalesky** [comment]
@jedwardwalters made some updates. Let me know if I missed anything.

**Comment by wsalesky** [comment]
@jedwardwalters Actually I see the chapter display on 119 is still a little odd. I will take a closer look.

**Comment by jedwardwalters** [comment]
@wsalesky I think all of these issues are pretty much resolved.
