### ISSUE TITLE
Table of Contents Box

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#69]
The table of contents box is not displaying anything on quite a few texts (for example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/1.html)

@wsalesky I will look and see if I can figure this out on my own and I'll keep you posted.

**Comment by wsalesky** [comment]
@jedwardwalters  I had noticed that as well, it was on my mental list, thanks for making an issue to track it.

**Comment by jedwardwalters** [comment]
@wsalesky I may have discovered the issue. I noticed that the TOC still works for a handful of texts. Here's an example:
Display: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/188
Code: https://github.com/srophe/syriac-corpus/blob/master/data/tei/188.xml

It looks like this text, and a few others I checked, are still using the old div1, div2 system that we had in place before we decided to use unnumbered divs. So, I think maybe the issue is that the TOC code may still be tied to the numbered div system?

**Comment by wsalesky** [comment]
@jedwardwalters thanks. I will change it.

**Comment by jedwardwalters** [comment]
Thanks. And I made an issue for myself to go through and change those texts that are still using div1, div2, etc.

**Comment by wsalesky** [comment]
I think this should be resolved now. Reopen if you find any remaining bugs or outliers.
