### ISSUE TITLE
Browse Options

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#7]
Please implement two basic browse forms (each with English and Syriac Options):

1. By Ancient Author (with A-Z tabs) use /TEI/teiHeader/fileDesc/titleStmt/author/@ref (please process the Syriaca.org URI to get the preferred name in English and Syriac)
2. By Title (A-Z tabs) (in the sorting on titles could it treat the numbers as numeric, so that the order is 1, 2, 3, not 1, 10, 11...) use /TEI/teiHeader/fileDesc/titleStmt/title[1]/@ref (please process the Syriaca.org URI to get the preferred title in English and Syriac)

**Comment by wsalesky** [comment]
Is the eventual plan for this application to have it's own server? Or will it always be sharing a repository with Syriaca.org?

**Comment by davidamichelson** [comment]
It will have its own server.

**Comment by wsalesky** [comment]
Initial code is up. Will require more testing as more records (with other titles and authors) are added.
