### ISSUE TITLE
Delete Extra Space in Source

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#70]
In the "Stable Identifiers" box, in the source section, there appears to be an extra space between the opening quotation mark (") and the title of the work. So, for example:

Source: D. Ioannes Parisot, ed. " Aphraatis Demonstrationes I-XXII." [Delete extra space before Aphraatis]
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/1.html

**Comment by wsalesky** [comment]
Fixed.
