### ISSUE TITLE
Another Source Display Issue

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#74]
The format of the source display is producing a weird result on some of the texts. See, for example:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/27

There is a "." after the editor's name, where I assume it's looking for a title within the larger title. But many of our sources won't have that element.

You can see the code here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/27.xml#L75

Compare with the following example, which does have a title of a work within the title of a volume:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/1.xml#L71

**Comment by wsalesky** [comment]
Resolved. Will be on the dev site next week.
