### ISSUE TITLE
Some other random display things

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#76]
1) For some reason, texts 228-258 do not have any of the boxes on the left (TOC, toggle buttons, etc). See for example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/258

2) Likewise, this new one doesn't have a TOC: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/332
-Nor do texts 259-331

**Comment by wsalesky** [comment]
@jedwardwalters There is no tei:head elements which is what the Table of Contents is generated on and none of the elements that the 'Show' box is using to toggle displays, such as numbered elements, lines, page breaks etc. We can change how these elements work in the xquery, but we should also make sure the TEI is standardized.

**Comment by jedwardwalters** [comment]
Thanks for letting me know. I’ll work on this.

**Comment by jedwardwalters** [comment]
@wsalesky I fixed the issue on 332.

The problem, as I'm now realizing, with 259-331 is that if we insert a head element, it would essentially defeat the purpose of our lg toggle display. The main purpose behind toggling those features is that people could copy and paste large chunks of material without the section numbers interrupting. So, I think we have to choose between a TOC and our toggle display, at least for these texts.

Texts 228-258 are another beast entirely. There was no information included in the transcription--not even the source! So that's why there are no breaks or headings or anything. I'll have to think about this some more.

**Comment by wsalesky** [comment]
@jedwardwalters Do I have an action item on this ticket? (Just doing my Monday ticket roundup)

**Comment by jedwardwalters** [comment]
This is resolved.
