### ISSUE TITLE
Author browse display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#77]
@wsalesky On the browse by author page (http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/browse.html), I'm wondering if there's a better display option than having every single work by that author. So, on the "A" page, would it be possible to just have "Aphrahat" listed, then if someone clicked on Aphrahat it would open a list of Aphrahat's titles?

Or, this may be easier and is related to another issue: what if instead of all the individual titles, it displayed the large work (i.e. for Aphrahat, it would just be The Demonstrations). That would make the display results a lot less cluttered. 

This would be really helpful for authors with multiple larger works, like Ephrem. So, under "E" it could show Ephrem "Hymns on Nisibis" (instead of each individual hymn title), then as more hymn cycles are added it would only show the larger item that contains individual works.

Thoughts?

**Comment by wsalesky** [comment]
@jedwardwalters I think this is possible. Let me experiment a little and get back to you.

**Comment by jedwardwalters** [comment]
Maybe this is what you're already working on, but would the same collapsable display you used on the Hugoye app (author browse) work here?

**Comment by wsalesky** [comment]
My first draft uses facets (the fastest way code and rendering wise): 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/browse.html?view=title

If you prefer the browse the way the we do it for Hugoye (with the collapsable display) then we can look into it. I think it will slow the browse down a little, but maybe not significantly.

**Comment by wsalesky** [comment]
@jedwardwalters Let me know what you think of the 'faceted' Author browse. If you prefer the Hugoye method with collapsable display we can change it.

**Comment by jedwardwalters** [comment]
I'm okay with this. I like that Hugoye appearance a bit better, but I'm also happy to let the faster version win out over my aesthetic preference.

**Comment by wsalesky** [comment]
We can do a test run of the other version to see how it runs. Let me get everything else checked off first.

**Comment by wsalesky** [comment]
I added a test browse with the expanding authors like Hugoye, let me know what you think of speed (not all the features are worked out correctly, such as paging, if you like it I will put a little more work into it.)

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/browse2.html?lang=&alpha-filter=ALL&view=author

Compare with:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/browse.html?lang=&alpha-filter=ALL&view=author

**Comment by jedwardwalters** [comment]
Thanks! I really like the expanding version. But before we make a decision, I'll also ask the syriaca module editors for their opinion.

**Comment by wsalesky** [comment]
@jedwardwalters Sounds good.

**Comment by jedwardwalters** [comment]
@wsalesky Okay, the other editors also prefer the expanding/collapsable option. Note: on the test page you sent me, the "minus" sign beside the name when they are collapsed is a bit confusing. I think the +/- thing needs to be reversed.

Thank you!

**Comment by jedwardwalters** [comment]
Also, I think the faceted search might make sense to keep on the Title index, and as we add more features (like dates of texts), we could add additional facets.

**Comment by wsalesky** [comment]
Okay, I will make the change and let you know when it is ready for testing. I'm going to default to a full list and then let users select from the 'ABC' menu options if they want. Currently the list is pretty short, so having it all on one page makes the most sense to me.

**Comment by jedwardwalters** [comment]
Thanks. And yes, I agree--it make sense to me to default to the full list.

**Comment by wsalesky** [comment]
Done. Let me know if you encounter any problems, it starts paging after the 25th author. We can change the default page to be smaller (15) if you want.
