### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#78]
Two issues of spacing:

1) I'm wondering if the toggle on the page break (pb) element could, in addition to showing the number, also come with hard carriage returns so that the text is broken up more clearly. In a long text the page numbers are a bit hard to see.

So, for example, on this example: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/337
If you look at the first page break in the text (129), I'd love for that pb 129 to show up on a line by itself when the pb is toggled. Is that possible? Or would we have to do something else with the encoding for that to happen?

2) I think it would be nice if there were some space--perhaps just one blank line--between div elements. On that same example used above there are two different div elements before the body of the text, and it would be nice to have some visual distinction between them. Here's a screenshot to show what I mean (it'd be nice to have a line space where I indicate in red):
<img width="791" alt="screen shot 2018-03-07 at 10 25 44 am 2" src="https://user-images.githubusercontent.com/11543800/37100868-1c392578-21f2-11e8-8bdd-fb9c0af26fc7.png">

**Comment by wsalesky** [comment]
@jedwardwalters how does that look?

**Comment by jedwardwalters** [comment]
That is perfect. Thank you! Closing this now.
