### ISSUE TITLE
Verse 1 display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#79]
On this example (and all other biblical texts), when you toggle the verse number, they all work correctly except for verse 1 in each chapter:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/119

The 1 always gets kicked to the left. I know this is a Right to Left language issue. Any ideas on how to fix it? Worst case scenario, maybe there's a way to just not display the 1 and let the verse numbers start with verse 2 (assuming everyone is smart enough to not need verse 1 labeled.

**Comment by wsalesky** [comment]
@jedwardwalters I've been experimenting with this one, so far no luck forcing it to display correctly, the rtl/ltr transitions cause all sorts of interesting knock-on effects. Will continue to experiment!

**Comment by jedwardwalters** [comment]
@wsalesky Okay. Thanks for letting me know. I guess worst case scenario, maybe there's an easy way to just make the 1 not show up at all?

**Comment by wsalesky** [comment]
@jedwardwalters Yes, we could do that, but I haven't given up quite yet. Squashing some other bugs right now and coming back to this one shortly.

**Comment by wsalesky** [comment]
@jedwardwalters I think I fixed it. http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/119

**Comment by jedwardwalters** [comment]
Awesome! Thank you.

**Comment by wsalesky** [comment]
Those bi-directional texts are tricky.
