### ISSUE TITLE
Author name at top 

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#82]
I've been meaning to make this an issue for weeks and I just keep forgetting. Can we display the author name in the title line for all the texts?. I think this will help. See attached photo:
<img width="1434" alt="screen shot 2018-03-10 at 4 22 34 pm" src="https://user-images.githubusercontent.com/11543800/37246887-e29c424c-247f-11e8-949f-414a16477ee9.png">

**Comment by wsalesky** [comment]
Added, will be live next week.

**Comment by jedwardwalters** [comment]
Great!

**Comment by jedwardwalters** [comment]
This looks great. Closing this now. Thanks!
