### ISSUE TITLE
Footnote display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#83]
Okay, this is an issue I've been putting off but that we need to work out: how to display footnotes.

Here's an example of a text with a footnote: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/340 

You can see it right in the middle. There's a dot that I think is displaying as the footnote reference, and then the "sic" is the content of the note. I produced this example by running the word document through the OxGarage automatic conversion, and I don't know if this is the best TEI structure for notes. You can see it here: https://github.com/srophe/syriac-corpus/blob/master/data/tei/340.xml#L139

In terms of display, Ideally I'd like for there to be 
1) a superscript number for the footnote
2) display the content of the note at the bottom of the page
3) If possible: a ref on the footnote number that, if clicked, would show the content of the note either in a permanent box on the right side or a pop up box that could be closed

**Comment by wsalesky** [comment]
Basics in place. I would like to do some work on CSS. (Will be on dev after conferences are over, early next week. )

**Comment by jedwardwalters** [comment]
@wsalesky Cool! By content display, do you mean that the "sic" is showing up on the right hand side? I assume that's what you mean.

1) Can the footnote reference (the superscripted 1 in the text) be a smaller font?
2) Is there a way to display/not display the footnote numbers in the toggle box? I can imagine that being useful to someone if it's not complicated.

I think that random 2 in the text is there by accident.

**Comment by wsalesky** [comment]
Yes, I mean the 'sic'. I'm working out a few text issues so hopefully this will work out. 

1. Yes
2. Yes I think I can add that as well. 

(And the 2 is actually in the text, I checked because it was confusing me.)

**Comment by wsalesky** [comment]
Added the toggle. I think to get the footnote to display correctly in the popup you will have to add an `xml:lang='en'`

**Comment by jedwardwalters** [comment]
Okay, that's not a problem. But what about if the text of the footnote is Syriac? Will that mess up the font display?

**Comment by wsalesky** [comment]
@jedwardwalters I will test it. Thanks for thinking of it.

**Comment by jedwardwalters** [comment]
I’m in the middle of prepping for classes, but sometime tomorrow I can put up another text that has more footnotes than this one for testing.

**Comment by wsalesky** [comment]
okay.

**Comment by jedwardwalters** [comment]
@wsalesky Okay, I finally got around to making a new file with more footnotes. I think it looks pretty good. You can see it here: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/341.html

I'm wondering if we should just right justify the notes, since I think a lot of them will look like this. What do you think?

**Comment by wsalesky** [comment]
@jedwardwalters  Take a look at it right aligned and let me know which you prefer.

**Comment by jedwardwalters** [comment]
I think I like it right justified. But let me run it by Dave and the others to get their thoughts.

Also: I assume that I would need to tag each p element in the notes with an xml:lang="syr" to make those footnote fonts adjustable?

**Comment by wsalesky** [comment]
Yes, the lang tag is important, if it is different from its parent lang. (otherwise it assumes it matches the parent) If the others like it, then go ahead and close it.

**Comment by jedwardwalters** [comment]
@wsalesky For testing purposes I just added two new texts (/342 and /343) with footnotes, and for these I tagged the p element inside the notes with xml:lang="syr".

**Comment by jedwardwalters** [comment]
@wsalesky I asked the Syriaca editors for any feedback on the footnote display. Here are a few from Dan:

1) the box is really big even when it doesn't contain much. Might there be a way to make it a bit smaller when possible? 
2) Because the pop up appears just to the right of the footnote number it covers the word footnoted. Since many of the footnotes in this text seem to have word variants, it would be really nice to see the word in the text and the variant in the footnote at the same time. 
3) Is there some place where we explain the "R" and "L" that appear in the footnotes? 
4) The footnotes include a period in most cases. Can we display that to the left of the variant instead of to the right of the variant?

I think fixing the first one will help with the second one (and I agree that the box is a bit large). I'll figure out what to do with number 3.

**Comment by wsalesky** [comment]
@jedwardwalters Updated. Please let me know what you think of the changes. (Smaller box, slightly higher so it does not cover the word, added an outline to make the small box easier to see. )

**Comment by jedwardwalters** [comment]
I think the box solution looks much better. Two other things, though: 1) in the notes at the bottom, there is a red box showing up around the footnote numbers, and 2) they are all left-justified instead of right-justified (I do think right is better).
