### ISSUE TITLE
Automatic page numbering

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#86]
@wsalesky I couldn't figure out how to do this with regex. Let's start with this one as a test: 
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/228

I put the model that I want to use in the text here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/228.xml#L106

So, that is page break to mark the beginning of page 1. Now, every time there is a 
![image](https://user-images.githubusercontent.com/11543800/38400866-5d5cb6d8-3920-11e8-8ced-ed8e76eb0aed.png), it should be replaced with that page break template with increasing sequential numbering. 

Let me know if you need anything else. The last page for this text should be page 83.

**Comment by wsalesky** [comment]
@jedwardwalters Do you run these through an XSLT to get the TEI? We could also add the page numbering logic to that workflow if you do.

**Comment by jedwardwalters** [comment]
I've recently been experimenting with using the automatic conversion through Ox Garage (on the TEI website). If I knew more about XSLT, I might be able to make that work. I'd be happy to learn.

**Comment by wsalesky** [comment]
Anything else you would like to automagically add? If we are going to write a XSLT we may as well go all out.

**Comment by jedwardwalters** [comment]
I can't think of anything at the moment. Unfortunately all the files are so inconsistently formatted, it seems unfeasible to write anything more comprehensive.

**Comment by wsalesky** [comment]
@jedwardwalters I added a update tool to the app. So far it only adds the page numbers, we can add additional processing if we find we need it. Just upload your file, it will run the replace and then you can save the output to github. Check for any knock-on effects. I checked and it looks okay, but you may find something I missed. 

Link: http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/modules/data-updates.xql

**Comment by jedwardwalters** [comment]
@wsalesky This worked great on my first trial run. 

Question: it numbered everything correctly, meaning that it started with page 2 (which is what I wanted it to do), but I assume that's only because I had a pb element in there already with n=1. Is that correct?

In other words, for all subsequent texts where the page number begins at higher numbers, if I manually put in the first page number, will it then number everything sequentially from whatever I identify as the first page number?

Specifically: this first text ends on folio 83. When I convert the second text I will want it to start with 83 and go up from there. Will that work?

**Comment by jedwardwalters** [comment]
Also, the form it rendered it in made it super easy to add in the correct ed reference with find/replace. So it works great as it is. I just want to be sure about the page numbering thing.

**Comment by wsalesky** [comment]
It adds empty tei:pb for every occurrence of '܀܀܀' and then goes back through and renumbers all the page breaks. So it won't matter if you have page breaks already or not. We can add additional data processing to this form if you find you need it.

**Comment by jedwardwalters** [comment]
Ah, I see. So it would automatically renumber everything starting from one. Yes, I think it would be helpful if you could make that change to the code. Either that or set up a way I can customize what number it starts from, since it will be different for every document.

**Comment by wsalesky** [comment]
I can do either way. It would probably be easiest for me code wise to just
start from numbered pb.

**Comment by jedwardwalters** [comment]
That's totally fine. I need to have the specific page number information anyway, so it's not a problem for me to manually add the first pb.

**Comment by wsalesky** [comment]
Okay, number the first tei:pb. It will use the first tei:pb/@n to start the numbering. I have updated the code, give it a try.

**Comment by jedwardwalters** [comment]
Just tested it and it works perfectly. This will save me soooo much time. Thank you!!!
