### ISSUE TITLE
Manuscript source display

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#87]
For our texts that come from manuscripts, not from printed editions, the source information is not showing. See:

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/30
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/102
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/228

(I gave three examples because they're all from different manuscripts--for display testing)

**Comment by wsalesky** [comment]
@jedwardwalters  What do you want the display for these to look like?

**Comment by wsalesky** [comment]
@jedwardwalters Updated. If it looks okay, please close the issue.

**Comment by jedwardwalters** [comment]
@wsalesky One quick thing: it looks like there's an extra space between the parentheses and the altidentifier name at the beginning and end:
( Vat. sir. 117 )
as opposed to
(Vat. sir. 117)

**Comment by wsalesky** [comment]
Updated

**Comment by jedwardwalters** [comment]
Just realized I missed something the first time. (Sorry...tired eyes).
The shelfmark isn't showing up after the repository.

So, text/30 should be: London, British Library Oriental 5463
text/26 should be: Vatican City, Vatican Library Syr. 117

**Comment by wsalesky** [comment]
How about now?

**Comment by jedwardwalters** [comment]
Perfect. Thanks.
