### ISSUE TITLE
Standardizing Print Edition Source

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#88]
@wsalesky One issue I'm not quite sure how to tackle is the standardization of the biblStruct section to describe the source material. If you look at the source description on these two pages, you'll see that there are formatting issues related to the kinds of information we have about the source:

http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/1
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/27

So, do I need to develop one single biblStruct pattern that can be used for all print editions? Or is there a way for your code to be customizable depending on what info is available? For example: sometimes a work is contained in a volume that has multiple works, sometimes a single work is the whole volume; sometimes we have page numbers, sometimes we don't; sometimes there's a series editor, sometimes there isn't; etc...

Based on your work with the other Syriaca platforms, is there a biblStruct pattern that you prefer? This is one of those case where the TEI guidelines are so flexible that they're actually a bit difficult to work with--there are too many options!

**Comment by wsalesky** [comment]
@jedwardwalters Is this still a question? I think @davidamichelson is probably a better resource on the TEI guidelines.

**Comment by jedwardwalters** [comment]
@wsalesky Yes, @davidamichelson and I have been talking about this a bit, though tangentially through other topics. So I'll unassign you and Dave and I can figure this out.

**Comment by wsalesky** [comment]
@jedwardwalters Okay, I suspect this is related: https://github.com/srophe/syriac-corpus-app/issues/87

I will wait to work on that until this one is resolved.

**Comment by jedwardwalters** [comment]
@wsalesky I think we have resolved these issues elsewhere.

**Comment by davidamichelson** [comment]
I think this can be closed?

**Comment by jedwardwalters** [comment]
Yes, I think so too.
