### ISSUE TITLE
Sample text link

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#89]
We need a link to a sample page from the landing page (like the other syriaca sites). How about this one?
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/345.html

**Comment by wsalesky** [comment]
Sure, how would you like to include this? 

Under the "About The Oxford-BYU Syriac Corpus project" ?  Do you want any explanatory text to go with the link?

**Comment by jedwardwalters** [comment]
Yes, that would be fine. I'm imagining we'll have a couple of more links to put here, sort of like what you find on the gazetteer page: http://www.syriaca.org/geo/index.html

I've asked Kristian and David to write a brief "history" of the project, so that's one link we could put there. We can also put a link for the (in-progress) guideline submissions, resources, etc.

**Comment by wsalesky** [comment]
@jedwardwalters Added. We can add a link to the guidelines when they are ready.

**Comment by jedwardwalters** [comment]
Great. I'll create a separate issue when we are ready to add other things.
