### ISSUE TITLE
Linked Data Box

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#90]
We'd like to add a Linked Data box--basically exactly what you did for e-GEDSH. I think it should go under the "How to Cite" box on the right.

**Comment by wsalesky** [comment]
@jedwardwalters are there links to Syriaca.org data? If so what is a good record to test this with?

**Comment by jedwardwalters** [comment]
Looks great. I noticed a few inconsistencies, but I'll close this issue now and raise those as separate items. They may all be code related, so I'll check on that before I post.
