### ISSUE TITLE
Corrections/Additions

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#91]
The Corrections/Additions box does not currently work (in chrome or firefox--we checked). And where will these messages be sent? Should I set up a dedicated email account or something?

Also, can we make it just say "Corrections?" instead of "Corrections/Additions?"

**Comment by wsalesky** [comment]
@jedwardwalters emails where this should be delivered? Also, you will need to set up a reCAPTCHA account once you have a production server and production URL.

**Comment by jedwardwalters** [comment]
I suppose for now these can just be sent to: jwalters@rc.edu

And okay re: reCAPTCHA

**Comment by wsalesky** [comment]
@jedwardwalters  This is now working, you should have received a test email from me this morning (reopen if you did not). To use the email function you will always need to drop the config file into the app after it has been deployed to eXist. I will send you a copy of the config file shortly.
