### ISSUE TITLE
Order of titles on author search page

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#93]
On the Author search page, when you expand an author (for example, Aphrahat), the results are not in numerical order. Is there something I need to do in the code?

**Comment by wsalesky** [comment]
Where is the numerical order specified, in the TEI?

**Comment by jedwardwalters** [comment]
Hmm. Good question. It may not be specified other than the number in the title. Any thoughts on where it would need to be?

**Comment by wsalesky** [comment]
Looks like you can use `@n` on the title element. I think that is how @nathangibson coded it in NHSL.

**Comment by jedwardwalters** [comment]
Okay. I'll work on that.

**Comment by nathangibson** [comment]
Off the top of my head, I don't remember using `@n` on the title element, but if it is relevant we did use `@n` on relations to sort works contained in other works. See the final listRelation in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/792/tei.

**Comment by wsalesky** [comment]
Oh, that is where it was. Thanks @nathangibson. @jedwardwalters  It is valid on the title element as well.

**Comment by jedwardwalters** [comment]
@wsalesky I added the '@n' element to files 1-24 (The Demonstrations) for testing.

**Comment by wsalesky** [comment]
@jedwardwalters This has been added. Please review and close if it meets your expectations.
