### ISSUE TITLE
Browse by Syriac title

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#94]
Can we add a browse by Syriac title feature? Since that's already incorporated in Syriaca, hopefully it's not too much additional work. Most titles in the corpus have a Syriac version. 

Note: if this needs to wait until after other things are done, that's fine.

**Comment by jedwardwalters** [comment]
I think having it in Syriac just like the Gazetteer page is perfect (same Syriac phrase and everything).

**Comment by wsalesky** [comment]
Added. Do you want the facets on the Syriac Title browse as well, or should I hide that? (If it looks good as is you can close this. )

**Comment by jedwardwalters** [comment]
This looks great. And yes, I think we can keep the facets.
