### ISSUE TITLE
Check author names in Corpus against Syriaca

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#96]
Double check to make sure standard spelling used here in the corpus is the base name used in Syriaca.org.

**Comment by jedwardwalters** [comment]
https://docs.google.com/spreadsheets/d/1PIXjFLAP_HNDgfsaErSo5fToipCliWntT_njwS6eDeI/edit?usp=sharing

Shared this link with syriaca editors for feedback.

**Comment by davidamichelson** [comment]
@wsalesky I made a change to the master branch of Srophe-App-Data for http://syriaca.org/person/321 (see https://github.com/srophe/srophe-app-data/commit/b7b12eb1ba4a565b85ac3ed7a711e3a137a0c791) but the webhooks do not seem to be pushing it to production.  Can you check please?

**Comment by wsalesky** [comment]
@davidamichelson I checked webhooks, they were not working correctly. I have them back up now. I re-pushed that change, please let me know if you see your changes.

**Comment by jedwardwalters** [comment]
I've made the corrections, but the webhooks still aren't working properly. @wsalesky when those changes get pushed, we can close this.

**Comment by wsalesky** [comment]
@jedwardwalters Sorry, is this corpus data? or Syriaca.org data? Dev server or production? Thanks

**Comment by jedwardwalters** [comment]
Oh, sorry for the confusion. Corpus data: production server. (pull request 194)

**Comment by wsalesky** [comment]
Okay I re-pushed them. I don't know why it failed. Please keep an eye on changes to production so I can do future troubleshooting if needed. Thanks!

**Comment by jedwardwalters** [comment]
Great. Closing this one down.
